---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret immich-garage-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
  data:
    - secretKey: REGION
      remoteRef:
        key: garage
        property: S3_REGION
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: garage/keys/immich
        property: ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: garage/keys/immich
        property: SECRET_ACCESS_KEY
