---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot
  namespace: longhorn-system
spec:
  cron: "*/15 * * * *"
  task: "snapshot"
  groups:
    - backup
  retain: 24
  concurrency: 3
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup
  namespace: longhorn-system
spec:
  cron: "0 0 * * *"
  task: "backup"
  groups:
    - backup
  retain: 7
  concurrency: 3
  parameters:
    full-backup-interval: "7"
