---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/storageclass-storage-v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-backup
  namespace: longhorn-system
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  recurringJobs: |
    [
      {
        "name":"snapshot",
        "isGroup":true
      }, {
        "name":"backup",
        "isGroup":true
      }
    ]
