---
apiVersion: etcd.aenix.io/v1alpha1
kind: EtcdCluster
metadata:
  name: gravity-etcd
  namespace: gravity
spec:
  replicas: 3
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn-backup
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
