---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gravity
  namespace: gravity
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      gravity:
        type: statefulset
        replicas: 1
        strategy: RollingUpdate

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/beryju/gravity
              tag: v0.27.1
            env:
              - name: BOOTSTRAP_ROLES
                value: dns;api;monitoring
              - name: INSTANCE_IP
                value: &ip ${DNS_IP}
              - name: INSTANCE_LISTEN
                value: 0.0.0.0
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz/live
                    port: 8009
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz/ready
                    port: 8009

    service:
      app:
        type: ClusterIP
        ports:
          http:
            port: 8008

      dns:
        type: LoadBalancer
        loadBalancerIP: *ip
        # externalTrafficPolicy: Local
        # allocateLoadBalancerNodePorts: false
        ports: &dns_ports
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP

      dns-ipv6:
        enabled: false
        type: LoadBalancer
        loadBalancerIP: "${DNS_IPv6}"
        ports: *dns_ports

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Gravity
          gethomepage.dev/icon: gravity
          gethomepage.dev/description: DNS with ad-blocking through Blocky
          gethomepage.dev/group: Network
        hosts:
          - host: &domain gravity.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *domain
            secretName: gravity-tls

    persistence:
      data:
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
