---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/apps.emqx.io/emqx_v2beta1.json
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: homeassistant-emqx
spec:
  image: public.ecr.aws/emqx/emqx:5.8.7
  config:
    data: |
      authentication {
        backend = "built_in_database"
        mechanism = "password_based"
        password_hash_algorithm {
            name = "bcrypt"
        }
        user_id_type = "username"
        bootstrap_file = "/opt/init-user.json"
        bootstrap_type = "plain"
      }
      authorization {
        sources = [
          {
            type = built_in_database
            enable = true
          }
        ]
        no_match: "deny"
      }
  coreTemplate:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
        reloader.stakater.com/rollout-strategy: restart
    spec:
      replicas: 1
      envFrom:
        - secretRef:
            name: homeassistant-emqx-secret
      extraVolumeMounts:
        - name: init-user
          subPath: init-user.json
          mountPath: /opt/init-user.json
          readOnly: true
        - name: init-user
          subPath: init-acl
          mountPath: /opt/init-acl
          readOnly: true
      extraVolumes:
        - name: init-user
          secret:
            secretName: homeassistant-emqx-init-user
  # listenersServiceTemplate:
  #   metadata:
  #     annotations:
  #       metallb.io/loadBalancerIPs: 192.168.10.83
  #   spec:
  #     type: LoadBalancer
