---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      radarr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 6020
            runAsGroup: 65537
            fsGroup: 65537
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.1.0.10316@sha256:ba33a817917792a589f1223e2da9d336692f9eb626b15ff8c7f06afcab4356bd
            env:
              # See: https://wiki.servarr.com/radarr/environment-variables
              TZ: ${TIME_ZONE}
              RADARR__APP__INSTANCENAME: Radarr
              RADARR__APP__THEME: dark
              RADARR__APPLICATION_URL: "https://{{ .Release.Name }}.${CLUSTER_DOMAIN}"
              RADARR__LOG__LEVEL: info
              RADARR__LOG__ANALYTICSENABLED: false
              RADARR__SERVER__PORT: &port 8080
              RADARR__UPDATE__BRANCH: develop
            # envFrom:
            #   - secretRef:
            #       name: radarr-secret
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
              readiness: *probe
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        existingClaim: radarr-config
      media:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/media
      tmp:
        type: emptyDir
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Radarr
          gethomepage.dev/icon: radarr
          gethomepage.dev/description: Movie organizer & manager
          gethomepage.dev/group: Media
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
