---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      lldap:
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/lldap/lldap
              tag: v0.6.2-alpine-rootless
            env:
              TZ: ${TIME_ZONE}
              UID: 65534
              GID: 65534
              LLDAP_LDAP_BASE_DN: ${LDAP_BASE_DN}
            envFrom:
              - secretRef:
                  name: lldap-secret
            probes:
              liveness: &probes
                enabled: true
                spec:
                  initialDelaySeconds: 1
              readiness: *probes
            resources:
              requests:
                cpu: 5m
                memory: 16Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: lldap
        ports:
          ldap:
            port: 389
            targetPort: 3890
            protocol: TCP
            primary: true
          http:
            port: 17170
            protocol: HTTP
    persistence:
      data:
        existingClaim: lldap-data
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: LLDAP
          gethomepage.dev/icon: lldap
          gethomepage.dev/description: Light LDAP implementation
          gethomepage.dev/group: Auth
        hosts:
          - host: &host lldap.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: lldap-tls
