---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      lldap:
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/lldap/lldap
              tag: v0.6.2-alpine-rootless
            probes:
              startup:
                enabled: true
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              TZ: ${TIME_ZONE}
              LLDAP_JWT_SECRET:
                secretKeyRef:
                  name: lldap-secret
                  key: jwt_secret
              LLDAP_KEY_SEED:
                secretKeyRef:
                  name: lldap-secret
                  key: key_seed
              LLDAP_LDAP_BASE_DN:
                secretKeyRef:
                  name: lldap-secret
                  key: ldap_base_dn
              LLDAP_LDAP_USER_PASS:
                secretKeyRef:
                  name: lldap-secret
                  key: ldap_user_pass
              UID: 65534
              GID: 65534
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: lldap
        ports:
          ldap:
            port: 3890
            targetPort: 389
            protocol: TCP
            primary: true
          http:
            port: 17170
            protocol: HTTP
    persistence:
      data:
        existingClaim: lldap-data
    ingress:
      app:
        className: traefik
        annotations:
          kubernetes.io/tls-acme: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: LLDAP
          gethomepage.dev/icon: lldap
          gethomepage.dev/description: Light LDAP implementation
          gethomepage.dev/group: Auth
        hosts:
          - host: &host lldap.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: lldap-tls
