---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      lldap:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 11001
            runAsGroup: 11001
            fsGroup: 11001
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/lldap/lldap
              tag: v0.6.2-alpine-rootless@sha256:35df821899ec54c11eaab395e9c68e191e2582592cba343b0a904f6821aadcd2
            env:
              TZ: ${TIME_ZONE}
              UID: 11001
              GID: 11001
              LLDAP_LDAP_BASE_DN: ${LDAP_BASE_DN}
            envFrom:
              - secretRef:
                  name: lldap-secret
            probes:
              liveness: &probes
                enabled: true
                spec:
                  initialDelaySeconds: 1
              readiness: *probes
            resources:
              requests:
                cpu: 5m
                memory: 16Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      data:
        existingClaim: lldap-data
    service:
      app:
        ports:
          ldap:
            port: 389
            targetPort: 3890
            protocol: TCP
            primary: true
          http:
            port: 17170
            protocol: HTTP
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: LLDAP
          gethomepage.dev/icon: lldap-dark
          gethomepage.dev/description: Light LDAP implementation
          gethomepage.dev/group: Auth
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
