---
route:
  receiver: ntfy
  group_by:
    - alertname
  routes:
    - matchers:
        - alertname =~ "Watchdog|InfoInhibitor"
      receiver: blackhole
receivers:
  - name: blackhole
    webhook_configs: []
  - name: ntfy
    webhook_configs:
      - url: http://alertmanager-ntfy.observability.svc.cluster.local:8000/hook
        http_config:
          basic_auth:
            username: "{{ .HTTP_USERNAME }}"
            password: "{{ .HTTP_PASSWORD }}"
