# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.35.2-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:CUwlMFlw0fMMDTw=,iv:DsOedL68O6FoGiQjO7fvYpTxfDztLrYjfVoc8OCSfns=,tag:4sbf4w3Z7aR80aVoc2zWwA==,type:str]
  ADMIN_EMAIL: ENC[AES256_GCM,data:0QrMBEsxCNrcFU2lLBq1U3OSCXyIPzykSZKFpg==,iv:ei6kr+/vWZtu4ds29GzY4ApyHAaOhlOQhKOI3dRyNqY=,tag:xeU8fmoqz7l98+dppZaEqA==,type:str]
  NTFY_ALERTMANAGER_TOPIC: ENC[AES256_GCM,data:blNufg6HTOUhgKiciTQXzyhyCvM/wHKf/4f7ZYvkt3YjnQ==,iv:CwbeZuK8mWwulKaJ2kic8El+9WBetEY7N6dHNiwzdWI=,tag:CTuji1JWqPd4wIrv+O5LaQ==,type:str]
sops:
  age:
    - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkLzc1TE85dTgxRUl0UXl1
        dEJuY3ZaVjY2SGdYUmpmdTVrYjF0VE5CSnhZCmFvMXQ3aG9aR1RGMXRTbWtWZ3Z2
        TEZnSjg3ZFNjOHRIczRvaEFpMFNxWUEKLS0tIFFtMFV2LzFvMzdCNStLOHBDOTlT
        VGpadmhjVXlrd3BScUFxNzJ0TXhVOHMKEyylzEQEfwwV+8C+B/+wWfxf6LSw3hKW
        VcY4aSwjEf0qkDxX/on5vWUsC+h57cuJfhhOvL2z6uBSk8iMbXzR4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T10:44:23Z"
  mac: ENC[AES256_GCM,data:Vfy8Gp5h2kfrQrcCfuBCI95FPdT5jNSYf+M0pow6LP/f31tO5sNAg3ODK8NYemfw3LFCw2dZCCxfrsPp4t29tAqsBB2lfjo71aFKvFxRJUlOSNH/8j6u3zItoEjKlmUwOOdsgUMJGY+6ha75qeyjEiHrLpGelyZ/6MQWeh0ROlw=,iv:EkFH30RrKiisGlREfPUTDJwAP+ppM4K7UxYbuV4hwhU=,tag:F6l5JpG2nPbaUeeCQTMmSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
