---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 6060
        runAsGroup: 6060
        fsGroup: 6060
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.6.1@sha256:e4690164cc4ed1bbd82adc00dd9aeed37bd49d938fe2f0ca46cb5082d05ddb71
            env:
              PUID: 6060
              GIUD: 6060
              TZ: ${TIME_ZONE}
              BASE_URL: https://mealie.${CLUSTER_DOMAIN}
              SMTP_HOST: maddy.default.svc.cluster.local
              SMTP_PORT: 2525
              SMTP_FROM_NAME: Mealie
              SMTP_FROM_EMAIL: noreply@mail.{CLUSTER_DOMAIN}
              SMTP_AUTH_STRATEGY: NONE
              OIDC_AUTH_ENABLED: true
              OIDC_CONFIGURATION_URL: https://authelia.${CLUSTER_DOMAIN}/.well-known/openid-configuration
              OIDC_CLIENT_ID: mealie
              OIDC_USER_GROUP: id_user
              OIDC_ADMIN_GROUP: id_admin
              OIDC_AUTO_REDIRECT: true
              OIDC_REMEMBER_ME: true
            envFrom:
              - secretRef:
                  name: mealie-secret
            resources:
              requests:
                memory: 256Mi
                cpu: 50m
              limits:
                memory: 512Mi
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        controller: *app
        ports:
          http:
            port: 9000
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Mealie
          gethomepage.dev/icon: mealie
          gethomepage.dev/description: Recipe manager and meal planner
          gethomepage.dev/group: Apps
        hosts:
          - host: &host mealie.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: mealie-tls
    persistence:
      data:
        existingClaim: mealie-data
        advancedMounts:
          mealie:
            app:
              - path: /app/data
