---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: victoria-metrics
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values: # https://docs.victoriametrics.com/helm/victoria-metrics-k8s-stack/#parameters
    fullnameOverride: victoria-metrics

    defaultDashboards:
      enabled: true
    grafana:
      enabled: false

    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeDns:
      enabled: false # because coredns instead
    coreDns:
      enabled: true

    victoria-metrics-operator:
      fullnameOverride: victoria-metrics-operator
      operator:
        enable_converter_ownership: true

    vmsingle:
      enabled: true
      spec:
        replicaCount: 1
        retentionPeriod: 10d
        storage:
          storageClassName: longhorn-victoria-metrics
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 64Gi
        extraArgs:
          maxLabelsPerTimeseries: "150"
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 1.5Gi
        # downsampling.period: 30d:1m,90d:5m,180d:30m,1y:1h,2y:4h,5y:12h,10y:1d
      ingress:
        enabled: false
      route:
        enabled: true
        parentRefs: &parentRefs
          - name: traefik-gateway
            namespace: network
            sectionName: websecure
        hostnames:
          - vm.${CLUSTER_DOMAIN}

    alertmanager:
      enabled: true
      spec:
        externalURL: https://alertmanager.${CLUSTER_DOMAIN}
        configSecret: alertmanager-config-secret
      ingress:
        enabled: false
      route:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: VMAlertmanager
          gethomepage.dev/icon: alertmanager
          gethomepage.dev/description: Collects, manages and sends alerts to receivers
          gethomepage.dev/group: Observability
          gethomepage.dev/pod-selector: app.kubernetes.io/name=vmalertmanager
        parentRefs: *parentRefs
        hostnames:
          - alertmanager.${CLUSTER_DOMAIN}

    vmalert:
      enabled: true
      spec:
        extraArgs:
          external.url: https://vm-alert.${CLUSTER_DOMAIN}
        evaluationInterval: 15s
      ingress:
        enabled: false
      route:
        enabled: true
        parentRefs: *parentRefs
        hostnames:
          - vm-alert.${CLUSTER_DOMAIN}

    vmagent:
      enabled: true
      spec:
        scrapeInterval: 20s
        inlineRelabelConfig:
          # # drop high cardinality labels
          # - action: labeldrop
          #   regex: ^(id|uid|pod_uid|image|ip|address|snapshot|backup)$
          # drop kubernetes labels
          - action: labeldrop
            regex: ^beta_kubernetes_io_
          - action: labeldrop
            regex: ^node(_role)?_kubernetes_io_
          # drop node feature discovery labels
          - action: labeldrop
            regex: ^feature_node_kubernetes_io_
          # drop k3s labels
          - action: labeldrop
            regex: ^p2p_k3s_cattle_io_enabled$
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            memory: 1Gi
      ingress:
        enabled: false
      route:
        enabled: true
        parentRefs: *parentRefs
        hostnames:
          - vm-agent.${CLUSTER_DOMAIN}
