---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-k8s-stack
  interval: 30m
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values: # https://docs.victoriametrics.com/helm/victoria-metrics-k8s-stack/#parameters
    fullnameOverride: victoria-metrics

    defaultDashboards:
      enabled: true
      annotations:
        grafana_folder: observability
    grafana:
      enabled: false

    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeDns:
      enabled: false # because coredns instead
    coreDns:
      enabled: true

    victoria-metrics-operator:
      fullnameOverride: victoria-metrics-operator
      operator:
        enable_converter_ownership: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 128Mi

    vmsingle:
      enabled: true
      spec:
        retentionPeriod: 10d
        storage:
          storageClassName: longhorn-victoria-metrics
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 64Gi
        extraArgs:
          maxLabelsPerTimeseries: "150"
        resources:
          requests:
            cpu: 500m
            memory: 1.5Gi
          limits:
            memory: 3Gi
        # downsampling.period: 30d:1m,90d:5m,180d:30m,1y:1h,2y:4h,5y:12h,10y:1d
      ingress:
        enabled: false
      route:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Victoria Metrics
          gethomepage.dev/icon: victoriametrics
          gethomepage.dev/description: Time series database and monitoring solution
          gethomepage.dev/group: Observability
          gethomepage.dev/pod-selector: app.kubernetes.io/name=vmsingle
        hostnames:
          - victoria-metrics.${CLUSTER_DOMAIN}
        extraRules:
          - filters:
              - type: RequestRedirect
                requestRedirect:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /vmui/
                  statusCode: 302
            matches:
              - path:
                  type: Exact
                  value: /
        parentRefs: &parentRefs
          - name: traefik-gateway
            namespace: network
            sectionName: websecure

    alertmanager:
      enabled: true
      spec:
        externalURL: https://alertmanager.${CLUSTER_DOMAIN}
        configSecret: alertmanager-config-secret
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            memory: 64Mi
        configReloaderResources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            memory: 32Mi
      ingress:
        enabled: false
      route:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Alertmanager
          gethomepage.dev/icon: alertmanager
          gethomepage.dev/description: Collects, manages and sends alerts to receivers
          gethomepage.dev/group: Observability
          gethomepage.dev/pod-selector: app.kubernetes.io/name=vmalertmanager
        hostnames:
          - alertmanager.${CLUSTER_DOMAIN}
        parentRefs: *parentRefs

    vmalert:
      enabled: true
      spec:
        extraArgs:
          external.url: https://vm-alert.${CLUSTER_DOMAIN}
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 128Mi
        evaluationInterval: 15s
      ingress:
        enabled: false
      route:
        enabled: true
        hostnames:
          - vm-alert.${CLUSTER_DOMAIN}
        parentRefs: *parentRefs

    vmagent:
      enabled: true
      spec:
        scrapeInterval: 20s
        inlineRelabelConfig:
          # # drop high cardinality labels
          # - action: labeldrop
          #   regex: ^(id|uid|pod_uid|image|ip|address|snapshot|backup)$
          # drop kubernetes labels
          - action: labeldrop
            regex: ^beta_kubernetes_io_
          - action: labeldrop
            regex: ^node(_role)?_kubernetes_io_
          # drop node feature discovery labels
          - action: labeldrop
            regex: ^feature_node_kubernetes_io_
          # drop k3s labels
          - action: labeldrop
            regex: ^p2p_k3s_cattle_io_enabled$
        resources:
          requests:
            cpu: 500m
            memory: 384Mi
          limits:
            memory: 768Mi
      ingress:
        enabled: false
      route:
        enabled: true
        hostnames:
          - vm-agent.${CLUSTER_DOMAIN}
        parentRefs: *parentRefs

    kube-state-metrics:
      resources:
        requests:
          cpu: 5m
          memory: 32Mi
        limits:
          memory: 256Mi

    prometheus-node-exporter:
      resources:
        requests:
          cpu: 10m
          memory: 24Mi
        limits:
          memory: 64Mi
