---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # See: https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/deployment/helm/node-feature-discovery/values.yaml
  values:
    master:
      resources:
        requests:
          cpu: 15m
          memory: 64Mi
        limits:
          memory: 128Mi

    worker:
      resources:
        requests:
          cpu: 5m
          memory: 32Mi
        limits:
          memory: 64Mi

    gc:
      resources:
        requests:
          cpu: 5m
          memory: 32Mi
        limits:
          memory: 64Mi

    prometheus:
      enable: true
