---
access_control:

  default_policy: deny

  rules:
    - domain: "*.${CLUSTER_DOMAIN}"
      policy: one_factor

session:
  cookies:
    - domain: ${CLUSTER_DOMAIN}
      authelia_url: https://authelia.${CLUSTER_DOMAIN}

server:
  disable_healthcheck: true
  endpoints:
    authz:
      forward-auth:
        implementation: ForwardAuth

authentication_backend:
  ldap:
    implementation: lldap
    address: ldap://lldap
    base_dn: ${LDAP_BASE_DN}
    user: uid=authelia,ou=people,${LDAP_BASE_DN}
    users_filter: '(&(objectClass=person)(firstname=*)({username_attribute}={input}))'
    groups_filter: '(member={dn})'
    attributes:
      extra:
        immich-quota:
          name: immich_quota
          multi_valued: false
          value_type: integer

definitions:
  user_attributes:
    immich_role:
      expression: >
        'id_admin' in groups ? 'admin' :
        'id_user' in groups ? 'user' : ''

identity_providers:
  oidc:
    claims_policies:
      immich_policy:
        custom_claims:
          immich_role:
            attribute: immich_role
          immich_quota:
            attribute: immich_quota
    scopes:
      immich:
        claims:
          - immich_role
          - immich_quota
    clients:
      - client_id: immich
        client_name: Immich
        client_secret: '{{ fileContent "/secrets/oidc-client-immich" }}'
        public: false
        authorization_policy: one_factor
        pre_configured_consent_duration: 1y
        require_pkce: false
        redirect_uris:
          - app.immich:///oauth-callback
          - https://immich.${CLUSTER_DOMAIN}/auth/login
          - https://immich.${CLUSTER_DOMAIN}/user-settings
        claims_policy: immich_policy
        scopes:
          - openid
          - profile
          - email
          - immich
        response_types:
          - code
        grant_types:
          - authorization_code
        id_token_signed_response_alg: RS256
        userinfo_signed_response_alg: RS256
        token_endpoint_auth_method: client_secret_post
    jwks:
      - key: |
          {{ fileContent "/secrets/oidc/tls.key" | nindent 10 }}
        certificate_chain: |
          {{ fileContent "/secrets/oidc/tls.crt" | nindent 10 }}

notifier:
  filesystem:
    filename: /data/notification.txt

storage:
  local:
    path: /data/db.sqlite3

telemetry:
  metrics:
    enabled: true
