---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: falco
spec:
  priority: 50
  config:  # https://github.com/falcosecurity/falco/blob/master/falco.yaml
    tty: true
    json_output: true
    json_include_output_property: true
    http_output:
      enabled: true
      url: http://falcosidekick:2801
    metrics:
      enabled: true
      interval: 1h
    webserver:
      enabled: true
      prometheus_metrics_enabled: true
---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: falco-raspberrypi
spec:
  priority: 90
  config:  # https://github.com/falcosecurity/falco/blob/master/falco.yaml
    engine:
      kind: kmod
  selector:
    matchLabels:
      kubernetes.io/hostname: raspberrypi
