---
extends: default
ignore: |
  *.sops.*
rules:
  indentation: enable
  line-length: disable
  truthy: {}
  comments:
    min-spaces-from-content: 2
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
