---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret alertmanager-ntfy-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
    template:
      templateFrom:
        - configMap:
            name: alertmanager-ntfy-config-template
            items:
              - key: config.yaml
  dataFrom:
    - extract:
        key: alertmanager-ntfy
