---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      flaresolverr:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000  # hardcoded in image
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.4.6@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
            env:
              TZ: ${TIME_ZONE}
              LOG_LEVEL: info
              PORT: &port 8191
              PROMETHEUS_ENABLED: "true"
              PROMETHEUS_PORT: &metricsPort 8192
            probes:
              liveness: &probes
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
    service:
      app:
        ports:
          http:
            port: *port
          metrics:
            port: *metricsPort
    serviceMonitor:
      app:
        service:
          name: flaresolverr
        endpoints:
          - port: metrics
    route:
      app:
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
            sectionName: websecure
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
