---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia
  namespace: flux-system
spec:
  path: /apps/authelia/authelia/app
  prune: true
  dependsOn:
    - name: prometheus-operator-crds
    - name: cert-manager
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 15m
  timeout: 5m
