---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret lldap-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
  data:
    - secretKey: LLDAP_LDAP_USER_PASS
      remoteRef:
        key: lldap
        property: LDAP_USER_PASS
    - secretKey: LLDAP_JWT_SECRET
      remoteRef:
        key: lldap
        property: JWT_SECRET
    - secretKey: LLDAP_KEY_SEED
      remoteRef:
        key: lldap
        property: KEY_SEED
