---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret mosquitto-passwd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        passwd: |-
          {{- range $secret := list .HCPY .HOME_ASSISTANT .RING_MQTT .ZIGBEE2MQTT }}
          {{- $data := fromJson $secret }}
          {{ $data.USERNAME }}:{{ $data.PASSWORD_HASH }}
          {{- end }}
  data:
    - secretKey: HCPY
      remoteRef:
        key: mosquitto/users/hcpy
    - secretKey: HOME_ASSISTANT
      remoteRef:
        key: mosquitto/users/homeassistant
    - secretKey: RING_MQTT
      remoteRef:
        key: mosquitto/users/ring-mqtt
    - secretKey: ZIGBEE2MQTT
      remoteRef:
        key: mosquitto/users/zigbee2mqtt
