---
upstreams:
  groups:
    default:
      - tcp-tls:dns.quad9.net
      - tcp-tls:1dot1dot1dot1.cloudflare-dns.com
bootstrapDns: tcp+udp:9.9.9.9
conditional:
  fallbackUpstream: false
  mapping:
    fritz.box: 192.168.178.1
    178.168.192.in-addr.arpa: 192.168.178.1
clientLookup:
  upstream: 192.168.178.1
blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.txt
    malware:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt
  clientGroupsBlock:
    default:
      - ads
      - malware
customDNS:
  mapping:
    ${CLUSTER_DOMAIN}: "${PROXY_IP},${PROXY_IPv6}"
caching:
  maxItemsCount: 10_000
  minTime: 60s
  maxTime: 600s
  cacheTimeNegative: 60s
redis:
  address: blocky-dragonfly:6379/1
prometheus:
  enable: true
ports:
  http: 4000
