---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:KMQlZM5vuJKK/zoJwLtC+sGuNsymZQJUlbQn/txI506yN5QCLF0P9A==,iv:tn/iO/X2oo/dhBJy9e9bo1Lnk3oBGWjS1bQogIdhmXw=,tag:LsFu9j2a+3eO2HuFZnBPcg==,type:str]
sops:
    age:
        - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRzJkbzJ1UEo3di90SWpQ
            TXI3cjcxaDZvdHNMa3BvMkhVR0NPMmdmUnc4CkNBWlc3aWVzSFp2ZkY0a2pkTjFy
            SjVxNzhabWpwVHBqRmpTcW9pRHpEdkUKLS0tIGhYUTc1bXUzSmhJZGtnZy80Mm5q
            dE5BOFhva2dOTWVEWThpY3B1dVlFaDAKzT7YHG/pT1iCOWoRrWPRdqxjLf1GtoO9
            vA/MeYqHAm2KNykql038b5CQzzmE5u7WewVsOASXMIjNaX5QxlLkdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T11:11:36Z"
    mac: ENC[AES256_GCM,data:weGKqQI0iXdPyArPEx39HD8sL2Rpkn7B6yaeTvzP2lwdC5QVemgsi8nboAzpns5LR6/NNW0OltveWZPOdyrD1OVqMfUTnsb0qpzAVpCy/xjFIMN5vEQlq8AA6dBL4CsGXa4cX8UPRqUU8yU2IHXFy/zCLGNQz2ST0efZAkKMwWY=,iv:N++0nKpD7ryPEpnPIxVSXiOnbHhhaM0pFUlcC7RUKBU=,tag:pTlp9isZwgeehcCBGmKYuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
