---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/policies.kyverno.io/validatingpolicy_v1.json
apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: require-resource-constraints
  annotations:
    policies.kyverno.io/title: Require all pods have resource constraints
    policies.kyverno.io/description: >-
      Ensures CPU/Memory requests and Memory limits are defined.
      CPU limits remain optional.
spec:
  validationActions: ["Audit"]
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["longhorn-system"]
  validations:
    - expression: >-
        object.spec.containers.all(c,
          c.?resources.?requests.?cpu.hasValue() &&
          c.?resources.?requests.?memory.hasValue() &&
          c.?resources.?limits.?memory.hasValue()
        )
      message: CPU + memory requests and memory limits are required for all containers.
    - expression: >-
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(c,
          c.?resources.?requests.?cpu.hasValue() &&
          c.?resources.?requests.?memory.hasValue() &&
          c.?resources.?limits.?memory.hasValue()
        )
      message: CPU + memory requests and memory limits are required for all initContainers.
