---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kyverno.io/clusterpolicy_v1.json
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-resource-limits
spec:
  validationFailureAction: Audit
  rules:
    - name: memory-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: Memory limits are required
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
