---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vaultwarden
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      vaultwarden:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.34.3@sha256:84fd8a47f58d79a1ad824c27be0a9492750c0fa5216b35c749863093bfa3c3d7
            env:
              DOMAIN: https://vault.${CLUSTER_DOMAIN}
              TZ: ${TIME_ZONE}
              SIGNUPS_ALLOWED: false
              SMTP_HOST: maddy.default.svc.cluster.local
              SMTP_PORT: 2525
              SMTP_SECURITY: "off"
              SMTP_TIMEOUT: 15
              SMTP_FROM_NAME: Vaultwarden
              SMTP_FROM: no-reply@mail.${CLUSTER_DOMAIN}
              WEBSOCKET_ENABLED: true
            envFrom:
              - secretRef:
                  name: vaultwarden-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /alive
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 1Gi  # needed for argon2
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 11002
        runAsGroup: 11002
        fsGroup: 11002
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Vaultwarden
          gethomepage.dev/icon: vaultwarden-light
          gethomepage.dev/description: Lightweight, self-hosted password manager
          gethomepage.dev/group: Apps
        hosts:
          - host: &domain vault.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *domain
            secretName: vaultwarden-tls
    persistence:
      data:
        existingClaim: vaultwarden-data
