---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            # runAsNonRoot: true
            runAsUser: 6100
            runAsGroup: 65537  # media
            fsGroup: 65537  # media
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.8@sha256:93227545077893cc9516f28b3adb733b67bc4691f41b6167428a2a0e3220b81c
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
              readiness: *probe
            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                memory: 6Gi
                squat.ai/vpu: "1"
            securityContext:
              # NOTE: This is needed for hwaccel per the docs: https://jellyfin.org/docs/general/post-install/transcoding/hardware-acceleration/rockchip/#linux-setups
              # I tried to make it work without, but was not able to.
              privileged: true
              # allowPrivilegeEscalation: true
              # seccompProfile:
              #   type: Unconfined
              # appArmorProfile:
              #   type: Unconfined
              # seLinuxOptions:
              #   level: "s0"
              # capabilities:
              #   add:
              #     - SYS_ADMIN      # For /sys access
              #     - IPC_LOCK       # For DMA buffers
              #     - SYS_RAWIO      # For register access
              #     - SYS_RESOURCE   # For memory allocation
              #     - DAC_READ_SEARCH
              #     - DAC_OVERRIDE
              #     - SETUID         # For privilege escalation if needed
              #     - SETGID
    persistence:
      config:
        existingClaim: jellyfin-config
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/media
        globalMounts:
          - path: /media
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /cache
      libmali:
        type: hostPath
        hostPath: /usr/lib/aarch64-linux-gnu/libmali.so.1.9.0
        hostPathType: File
        globalMounts:
          - path: /usr/lib/aarch64-linux-gnu/libmali.so
            readOnly: true
    service:
      app:
        ports:
          http:
            port: *port
          # discovery:
          #   port: 7359
          #   protocol: UDP
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Jellyfin
          gethomepage.dev/icon: jellyfin
          gethomepage.dev/description: Open-source Media Server
          gethomepage.dev/group: Media
          gethomepage.dev/widget.type: jellyfin
          gethomepage.dev/widget.version: "2"
          gethomepage.dev/widget.url: https://{{ .Release.Name }}.${CLUSTER_DOMAIN}
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}` }}"
          gethomepage.dev/widget.enableBlocks: "true"
          gethomepage.dev/widget.enableNowPlaying: "false"
          gethomepage.dev/widget.enableMediaControl: "false"
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
        parentRefs:
          - name: traefik-gateway
            namespace: network
            sectionName: websecure
