---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIME_ZONE: Europe/Amsterdam
  SERVICE_CIDR: 10.43.0.0/16
  CLUSTER_CIDR: 10.42.0.0/16
