---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:yKh4YipUWiL/7OY=,iv:MJAIdU3fjhY/J3IyRHSZiM35GEoFYo7bxVzW5wDXo68=,tag:fgR8RFJf8IkeyXNUXuBghg==,type:str]
  SECRET_EMAIL: ENC[AES256_GCM,data:tT+kLGjNayAJJREulQoqTf6blRBr+0+FP8l6lg==,iv:E1yarWeqoqq9glEky90mXqXOSDcQNQHdQleppp9OjWI=,tag:lWbieyg3Ol1h2rSO3szNVg==,type:str]
  LB_IP_POOL: ENC[AES256_GCM,data:45DOfUmSVdLmUSnOn7bIZ0d10SFOyAfqYKBpOKcSwg==,iv:wR4diEyd9Gr8W7jfrjFy+aLohDWMhHaxvFxKAbDBiKI=,tag:I/AaSWFPaMjgXWR9YSUJKA==,type:str]
  LB_IPv6_POOL: ENC[AES256_GCM,data:ePTYC2fuuvw4wIOs6GImcLHXlADqQ3Da,iv:ml5Xb0crN7GnB+AmkQJPVUSksmnHE0Odqb02naFvRGU=,tag:IvOFl1avl+2lpzNpY5v5jw==,type:str]
  DNS_IP: ENC[AES256_GCM,data:IurogU9WmQuAJv5UsH7+,iv:nw1WE2jK8QxV8F3r/Xm6EXZ3xVraGoroTzzOjJGcldM=,tag:i+TPtggE3kFzc826gI1gcQ==,type:str]
  DNS_IPv6: ENC[AES256_GCM,data:iR/DasAa8Ot+jZRrDvUFGFVpsk4W,iv:WOT0rNWyitj2ioNFwz96e6knLoow7/Ch5wPEuohV8ek=,tag:X/VP9KGvb09pxopB5cELuQ==,type:str]
  PROXY_IP: ENC[AES256_GCM,data:b34Bo4tgeRtAK9rTGcaJ,iv:VnhW0kjLbemNZjud8rChOeNh+RYKzsUA4m0M9pGggQ4=,tag:C1/2nlmRSiyECIifH5rkrQ==,type:str]
  PROXY_IPv6: ENC[AES256_GCM,data:skTTIY4vFr23ul3VJk28Lc0gXNlf,iv:NNNCQByGUJni3qhL7uvnttLwK9sth0cONFywQG34cSA=,tag:D7Eb7vom9RJGQ9d09Tmabg==,type:str]
sops:
  age:
    - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkLzc1TE85dTgxRUl0UXl1
        dEJuY3ZaVjY2SGdYUmpmdTVrYjF0VE5CSnhZCmFvMXQ3aG9aR1RGMXRTbWtWZ3Z2
        TEZnSjg3ZFNjOHRIczRvaEFpMFNxWUEKLS0tIFFtMFV2LzFvMzdCNStLOHBDOTlT
        VGpadmhjVXlrd3BScUFxNzJ0TXhVOHMKEyylzEQEfwwV+8C+B/+wWfxf6LSw3hKW
        VcY4aSwjEf0qkDxX/on5vWUsC+h57cuJfhhOvL2z6uBSk8iMbXzR4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-30T16:12:21Z"
  mac: ENC[AES256_GCM,data:lcA48lFyY3uua7yCBcf4xiT0ZSzctDkHX7kl4AoMbMwfdFGgY6gzmugJpGO9PdrA32kV7kK1gtr9VQX1Z3ypDI9h5Yuu/PEm/5wgjjqJlVtFBUMAME9vI0VIZBZlVons2ohPWo9Kck8TC7tBS2lXOCTFggxsImQul3EPb8SNA9c=,iv:T2rm6Oe39MbiRNZpgSnCvRTTKeQiPyQYZxNw3irRjLI=,tag:OonyEYCcdol2PMqaQHIEDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
