---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:yKh4YipUWiL/7OY=,iv:MJAIdU3fjhY/J3IyRHSZiM35GEoFYo7bxVzW5wDXo68=,tag:fgR8RFJf8IkeyXNUXuBghg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:tT+kLGjNayAJJREulQoqTf6blRBr+0+FP8l6lg==,iv:E1yarWeqoqq9glEky90mXqXOSDcQNQHdQleppp9OjWI=,tag:lWbieyg3Ol1h2rSO3szNVg==,type:str]
    PROXY_IP: ENC[AES256_GCM,data:b34Bo4tgeRtAK9rTGcaJ,iv:VnhW0kjLbemNZjud8rChOeNh+RYKzsUA4m0M9pGggQ4=,tag:C1/2nlmRSiyECIifH5rkrQ==,type:str]
    PROXY_IPv6: ENC[AES256_GCM,data:skTTIY4vFr23ul3VJk28Lc0gXNlf,iv:NNNCQByGUJni3qhL7uvnttLwK9sth0cONFywQG34cSA=,tag:D7Eb7vom9RJGQ9d09Tmabg==,type:str]
sops:
    age:
        - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkLzc1TE85dTgxRUl0UXl1
            dEJuY3ZaVjY2SGdYUmpmdTVrYjF0VE5CSnhZCmFvMXQ3aG9aR1RGMXRTbWtWZ3Z2
            TEZnSjg3ZFNjOHRIczRvaEFpMFNxWUEKLS0tIFFtMFV2LzFvMzdCNStLOHBDOTlT
            VGpadmhjVXlrd3BScUFxNzJ0TXhVOHMKEyylzEQEfwwV+8C+B/+wWfxf6LSw3hKW
            VcY4aSwjEf0qkDxX/on5vWUsC+h57cuJfhhOvL2z6uBSk8iMbXzR4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T08:31:05Z"
    mac: ENC[AES256_GCM,data:md91LfMBVCTgi4cexQWVz7IznKc7gU8WYVUC7hoM7rcQqIwR0Gxzl7N1SAM907zGRNUq6mN6G2dTXu2KMCn5f788j2fsMwZRSF9FY+xmwvZHCEhSYggiiUieg6B4zCF9HYU0rvQKTIVjHuBCx6TALpTPn15GJ8ieUe3powXCpw0=,iv:+fZ/h8LWhGpTfRTjYNXA0/j+5NVuxNHmykTIfhW28iA=,tag:0OqqOgmxIWYmtQN97GVORA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
