---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 75.15.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: Skip  # handled by prometheus-operator-crds
  upgrade:
    crds: Skip  # handled by prometheus-operator-crds
  values:
    cleanPrometheusOperatorObjectNames: true

    alertmanager:
      enabled: false

    grafana:
      admin:
        existingSecret: grafana-secrets
        userKey: admin.user
        passwordKey: admin.password

      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Grafana
          gethomepage.dev/icon: grafana
          gethomepage.dev/description: Real-time monitoring with custom dashboards
          gethomepage.dev/group: Observability
          gethomepage.dev/pod-selector: app.kubernetes.io/name=grafana
        hosts:
          - &grafana_domain grafana.${SECRET_DOMAIN}
        path: /
        tls:
          - hosts:
              - *grafana_domain
            secretName: grafana-tls

      # Required to add additional dashboards via config
      # TODO: move to Grafana Operator and deploy dashboards as CRDs
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: default
              orgId: 1
              folder: ''
              type: file
              disableDeletion: true
              editable: false
              options:
                path: /var/lib/grafana/dashboards/default

      dashboards:
        default:
          longhorn:
            gnetId: 16888
            revision: 9
          traefik:
            gnetId: 17346
            revision: 9
          metallb:
            gnetId: 20162
            revision: 6
            datasource:
              - name: DS_PROMETHEUS
                value: Prometheus
          blocky:
            gnetId: 13768
            revision: 6
            datasource:
              - name: DS_PROMETHEUS
                value: Prometheus
              - name: VAR_BLOCKY_URL
                value: 'https:\/\/blocky.${SECRET_DOMAIN}'
          cert-manager:
            url: https://gitlab.com/uneeq-oss/cert-manager-mixin/-/raw/master/dashboards/cert-manager.json
            datasource: Prometheus
          flux-cluster:
            url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/cluster.json
            datasource: Prometheus
          flux-control-plane:
            url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/control-plane.json
            datasource: Prometheus

    prometheus:
      prometheusSpec:
        ruleSelector: &match_all
          matchLabels: ~
        serviceMonitorSelector: *match_all
        serviceMonitorNamespaceSelector: *match_all
        podMonitorSelector: *match_all
        scrapeConfigSelector: *match_all
        probeSelector: *match_all
