---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/mcsrobert/homelab
        - Asus RT-AX86S:
            - abbr: RT
              href: https://asus-wifi-router.fritz.box:8443
  custom.css: |
    .information-widget-longhorn-node {
        margin-left: 1rem; /* Equivalent to ml-4 */ !important
    }
  custom.js: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system.svc.cluster.local
  services.yaml: |
    - Smart Home:
        - Home Assistant:
            href: https://ha.${SECRET_DOMAIN}/
            description: Local smart home control and automation.
            icon: home-assistant
            namespace: ha-mqtt
            app: homeassistant
        - Mosquitto:
            description: Lightweight MQTT Server.
            icon: mosquitto
            namespace: ha-mqtt
            app: mosquitto
        - ZigBee2MQTT:
            href: https://z2m.${SECRET_DOMAIN}/
            description: Bridge Zigbee devices to MQTT.
            icon: zigbee2mqtt
            namespace: ha-mqtt
            app: zigbee2mqtt
        - Ring-MQTT:
            description: Bridge the Ring API to MQTT.
            icon: si-ring
            namespace: ha-mqtt
            app: ring-mqtt
    # - Media:
    #     - Jellyfin:
    #         href: https://jellyfin.${SECRET_DOMAIN}/
    #         description: Self-hosted media center for streaming movies, shows, music.
    #         icon: jellyfin
    #         namespace: jellyfin
    #         app: jellyfin
    #         {# widget:
    #           type: jellyfin
    #           url: https://jellyfin.${SECRET_DOMAIN}
    #           key: {{ secrets.jellyfin.token }}
    #           enableBlocks: true
    #           enableNowPlaying: true
    #           enableUser: true
    #           showEpisodeNumber: true #}
    - Administration:
        - Stirling-PDF:
            href: https://pdf.${SECRET_DOMAIN}/
            description: Self-hosted PDF conversion and editing tools
            icon: stirling-pdf
            namespace: stirling-pdf
            app: stirling-pdf-chart
    - Security:
        - Vaultwarden:
            href: https://vault.${SECRET_DOMAIN}/
            description: Lightweight, self-hosted password manager
            icon: vaultwarden-light
            namespace: vaultwarden
            app: vaultwarden
        # - Authentik:
        #     href: https://{{ domains.authentik }}/
        #     description: Self-hosted authentication, SSO, and access control.
        #     icon: authentik
        #     namespace: authentik
        #     app: authentik
        #     widget:
        #       type: authentik
        #       url: https://{{ domains.authentik }}/
        #       key: {{ secrets.authentik.token }}
    - Infrastructure:
        - MetalLB:
            description: Bare-metal load-balancing for Kubernetes
            icon: metallb
            namespace: metallb-system
            app: metallb
        - Traefik:
            description: Modern reverse proxy for applications
            icon: traefik-proxy
            namespace: traefik
            app: traefik
    - Observability:
        - Prometheus:
            description: Metrics and time-series database
            icon: prometheus
            namespace: observability
            app: prometheus
    - Network:
        - FRITZ!Box 5590:
            href: http://fritz.box
            description: Fiber modem and WiFi 6 router
            icon: avm-fritzbox
            widget:
              type: fritzbox
              url: http://192.168.178.1
        - Tailscale:
            href: https://login.tailscale.com/admin/machines
            description: Zero-config VPN with WireGuard.
            icon: tailscale
            namespace: tailscale
            app: tailscale
            podSelector: ""
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "total"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
