---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: uninstall
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      homepage:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.4.0
            resources:
              requests:
                cpu: 5m
                memory: 64Mi
              limits:
                memory: 128Mi
            env:
              LOG_TARGETS: stdout
              HOMEPAGE_ALLOWED_HOSTS: &domain homepage.${SECRET_DOMAIN}
            # envFrom:
            #   - secretRef:
            #       name: homepage-secret
        serviceAccount:
          identifier: homepage

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: *domain
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *domain
            secretName: homepage-tls

    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: custom.css
            path: /app/config/custom.css
          - subPath: custom.js
            path: /app/config/custom.js
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml

    serviceAccount:
      homepage: {}
