---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - configmap.yaml
  - rbac.yaml
  - helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: &app homepage
  app.kubernetes.io/instance: *app
