---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app flux-web
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator
  interval: 1h
  values:
    fullnameOverride: *app
    installCRDs: false
    web:
      serverOnly: true
