---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
data:
  TZ: ${TIME_ZONE}
  UPLOAD_LOCATION: /usr/src/app/upload
  # URLs
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
  IMMICH_SERVER_URL: http://immich-server:2283
  PUBLIC_IMMICH_SERVER_URL: https://immich.${SECRET_DOMAIN}
  # Redis
  REDIS_HOSTNAME: immich-dragonfly
  # Postgres
  DB_HOSTNAME: immich-cloudnative-pg-rw
