---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-server
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      immich-server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.3.1@sha256:f8d06a32b1b2a81053d78e40bf8e35236b9faefb5c3903ce9ca8712c9ed78445
            env:
              DB_USERNAME:
                secretKeyRef:
                  name: immich-cloudnative-pg-app
                  key: username
              DB_PASSWORD:
                secretKeyRef:
                  name: immich-cloudnative-pg-app
                  key: password
              REDIS_PASSWORD:
                secretKeyRef:
                  name: immich-dragonfly-secret
                  key: password
            envFrom:
              - configMapRef:
                  name: immich-config
              - secretRef:
                  name: immich-secret
    persistence:
      library:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/immich
        globalMounts:
          - path: /usr/src/app/upload
    service:
      app:
        ports:
          http:
            port: 2283
            protocol: HTTP
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Immich
          gethomepage.dev/icon: immich
          gethomepage.dev/description: High performance self-hosted photo and video management solution
          gethomepage.dev/group: Media
        hostnames:
          - immich.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: app
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
