---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-server
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      immich-server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.141.1@sha256:6d48910532cb8e2bc85737e52a633c2e65eeb499f6307e106cd131c5778ec634
            env:
              DB_USERNAME:
                secretKeyRef:
                  name: immich-cloudnative-pg-app
                  key: username
              DB_PASSWORD:
                secretKeyRef:
                  name: immich-cloudnative-pg-app
                  key: password
              REDIS_PASSWORD:
                secretKeyRef:
                  name: immich-dragonfly-secret
                  key: password
            envFrom:
              - configMapRef:
                  name: immich-config
              - secretRef:
                  name: immich-secret
    service:
      app:
        controller: immich-server
        ports:
          http:
            port: 2283
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Immich
          gethomepage.dev/icon: immich
          gethomepage.dev/description: High performance self-hosted photo and video management solution
          gethomepage.dev/group: Media
        hosts:
          - host: &host immich.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: immich-tls
    persistence:
      library:
        existingClaim: immich-library
        advancedMounts:
          immich-server:
            app:
              - path: /usr/src/app/upload
