---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      server:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 11100
            runAsGroup: &nfsGroup 65539
            fsGroup: *nfsGroup
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.4.1@sha256:e6a6298e67ae077808fdb7d8d5565955f60b0708191576143fc02d30ab1389d1
            env:
              !!merge <<: &sharedEnv
                TZ: ${TIME_ZONE}
                PUBLIC_IMMICH_SERVER_URL: https://immich.${CLUSTER_DOMAIN}
                IMMICH_SERVER_URL: http://immich-server:2283
                IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
                DB_URL:
                  secretKeyRef:
                    name: immich-cnpg-app
                    key: uri
              UPLOAD_LOCATION: &uploadPath /usr/src/app/upload
              REDIS_URL:
                secretKeyRef:
                  name: immich-dragonfly-secret
                  key: uri
            envFrom: &envFrom
              - secretRef:
                  name: immich-secret
            probes: &probes
              liveness: &probe
                enabled: true
              readiness: *probe
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 2Gi
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            # TODO: Once I get Talos and the RKNPU working, make this better
            # Probably want to use the generic-device-plugin at that point
            feature.node.kubernetes.io/cpu-model.family: "47"
          securityContext:
            runAsUser: 11110
            runAsGroup: 11110
            fsGroup: 11110
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.4.1@sha256:b3deefd1826f113824e9d7bc30d905e7f823535887d03f869330946b6db3b44a
            env:
              !!merge <<: *sharedEnv
              # TODO: make this work
              # Right now RKNPU is too old
              MACHINE_LEARNING_RKNN: "true"
              MACHINE_LEARNING_RKNN_THREADS: "2"
            envFrom: *envFrom
            probes: *probes
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
            securityContext: *securityContext
    persistence:
      upload:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/immich
        advancedMounts:
          server:
            app:
              - path: *uploadPath
      tmpfs:
        type: emptyDir
        advancedMounts:
          machine-learning:
            app:
              - path: /cache
                subPath: cache
              - path: /.cache
                subPath: internal-cache
              - path: /.config
                subPath: config
              - path: /tmp
                subPath: tmp
    service:
      server:
        controller: server
        ports:
          http:
            port: &port 2283
            primary: true
          api-metrics:
            port: 8081
          microservices-metrics:
            port: 8082
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
    serviceMonitors:
      server:
        service:
          identifier: server
        endpoints:
          - port: api-metrics
            path: /metrics
            interval: 1m
          - port: microservices-metrics
            path: /metrics
            interval: 1m
    route:
      server:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Immich
          gethomepage.dev/icon: immich
          gethomepage.dev/description: High performance self-hosted photo and video management solution
          gethomepage.dev/group: Media
          gethomepage.dev/pod-selector: >-
            app.kubernetes.io/instance in (
              immich,
              immich-cnpg,
              immich-dragonfly
            )
        hostnames:
          - immich.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: server
                port: *port
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
            sectionName: websecure
