---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret isponsorblocktv-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.json: |
          {
            "devices": {{ .DEVICES }},
            "apikey": "",
            "skip_categories": [
                "sponsor",
                "selfpromo",
                "exclusive_access",
                "interaction",
                "poi_highlight",
                "intro",
                "outro",
                "preview",
                "filler"
            ],
            "channel_whitelist": [],
            "skip_count_tracking": false,
            "mute_ads": true,
            "skip_ads": true
          }
  data:
    - secretKey: DEVICES
      remoteRef:
        key: isponsorblocktv
        property: DEVICES
