---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app generic-device-plugin
  namespace: system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      generic-device-plugin:
        type: daemonset
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/squat/generic-device-plugin
              tag: a4eabe9fbda65b11afe5a745093730ca7d468c26@sha256:8f4b616ff1ef70126be150fab41d4bb4445c80469b6cd8a1ca5a6c3e1c7f111d
            args:
              - --log-level=debug
              - --config=/config/config.yaml
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            # Apparently necessary to avoid some conflict in /dev?
            # terminationMessagePath: /tmp/term
            securityContext:
              privileged: true
              readOnlyRootFilesystem: true
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
            protocol: HTTP
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - interval: 30s
            path: /metrics
            port: http
            scrapeTimeout: 10s
    persistence:
      config:
        type: configMap
        name: generic-device-plugin-config
      dev:
        type: hostPath
        hostPath: /dev
      var-lib-kubelet-device-plugins:
        type: hostPath
        hostPath: /var/lib/kubelet/device-plugins
