---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret qbittorrent-gluetun-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
  data:
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: homelab/prd/proton-vpn
        property: WIREGUARD_PUBLIC_KEY
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: homelab/prd/proton-vpn
        property: WIREGUARD_PRIVATE_KEY
    - secretKey: UPDATER_PROTONVPN_EMAIL
      remoteRef:
        key: homelab/prd/proton-vpn
        property: EMAIL
    - secretKey: UPDATER_PROTONVPN_PASSWORD
      remoteRef:
        key: homelab/prd/proton-vpn
        property: PASSWORD
