---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret authelia-env-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: 'uid={{ .LLDAP_USERNAME }},ou=people,${LDAP_BASE_DN}'
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: '{{ .LLDAP_PASSWORD }}'
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: '{{ .IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}'
        AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: '{{ .IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET }}'
        AUTHELIA_SESSION_SECRET: '{{ .SESSION_SECRET }}'
        AUTHELIA_STORAGE_ENCRYPTION_KEY: '{{ .STORAGE_ENCRYPTION_KEY }}'
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: lldap/users/authelia
      rewrite:
        - regexp:
            source: "(.*)"
            target: LLDAP_$1
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret authelia-oidc-client-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
  data:
    - secretKey: grafana.secret
      remoteRef:
        key: authelia/oidc/grafana
        property: CLIENT_SECRET_HASH
    - secretKey: immich.secret
      remoteRef:
        key: authelia/oidc/immich
        property: CLIENT_SECRET_HASH
    - secretKey: jellyfin.secret
      remoteRef:
        key: authelia/oidc/jellyfin
        property: CLIENT_SECRET_HASH
    - secretKey: mealie.secret
      remoteRef:
        key: authelia/oidc/mealie
        property: CLIENT_SECRET_HASH
    - secretKey: renovate-operator.secret
      remoteRef:
        key: authelia/oidc/renovate-operator
        property: CLIENT_SECRET_HASH
