---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app maddy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      smtp-relay:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mcsrobert/maddy
              tag: 0.8.1-hotfix1@sha256:3599e254228ad1807076dd88a6a85d13cd0aeaebfaa4ebd9842dd589ff33879b
            env:
              TZ: ${TIME_ZONE}
              SMTP_PORT: &port 2525
              METRICS_PORT: &metricsPort 9000
            envFrom:
              - secretRef:
                  name: simple-mail-service-secret
            probes:
              startup: &probe
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - "echo -e 'EHLO localhost\r\nQUIT\r\n' | nc -w 5 127.0.0.1 $SMTP_PORT"
              readiness: *probe
              liveness: *probe
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 13000
        runAsGroup: 13000
        fsGroup: 13000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    service:
      app:
        ports:
          smtp:
            port: *port
            protocol: TCP
            primary: true
          metrics:
            port: *metricsPort
            protocol: HTTP
    serviceMonitor:
      app:
        endpoints:
          - port: metrics
    persistence:
      config:
        type: configMap
        name: maddy-config
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
