---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smtp-relay
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      smtp-relay:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/foxcpp/maddy
              tag: 0.8.1
            env:
              TZ: ${TIME_ZONE}
              SMTP_RELAY_SMTP_PORT: &port 2525
              SMTP_RELAY_METRICS_PORT: &metricsPort 9000
              SMTP_RELAY_SERVER: send.simplemailservice.eu
              SMTP_RELAY_SERVER_PORT: 465
            envFrom:
              - secretRef:
                  name: smtp-relay-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 13000
        runAsGroup: 13000
        fsGroup: 13000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    service:
      app:
        ports:
          smtp:
            port: *port
            protocol: TCP
            primary: true
          metrics:
            port: *metricsPort
            protocol: HTTP
    serviceMonitor:
      app:
        endpoints:
          - port: metrics
    persistence:
      config:
        type: configMap
        name: smtp-relay-config
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
