---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
  path: /apps/database/dragonfly-operator/app
  interval: 30m
  prune: true
  targetNamespace: database
  sourceRef:
    kind: GitRepository
    name: flux-system
