---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret grafana-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: authelia/oidc/grafana
        property: CLIENT_SECRET
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana/admin
        property: USERNAME
    - secretKey: admin-password
      remoteRef:
        key: grafana/admin
        property: PASSWORD
