---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      sonarr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 6030
            runAsGroup: 65537
            fsGroup: 65537
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          sonarr:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.18.2978@sha256:2cd77fb3d81909a734d61bb8f71462044cb9d2f187e626a28a05a5c4e4be8fd2
            env:  # See: https://wiki.servarr.com/sonarr/environment-variables
              TZ: ${TIME_ZONE}
              SONARR__APP__INSTANCENAME: "{{ .Release.Name }}"
              SONARR__APP__THEME: dark
              SONARR__APPLICATION_URL: https://{{ .Release.Name }}.${CLUSTER_DOMAIN}
              SONARR__LOG__LEVEL: info
              SONARR__LOG__ANALYTICSENABLED: false
              SONARR__SERVER__PORT: &port 8080
              SONARR__UPDATE__BRANCH: develop
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
              readiness: *probe
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        existingClaim: sonarr-config
      media:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/media
      tmp:
        type: emptyDir
    service:
      sonarr:
        ports:
          http:
            port: *port
    route:
      sonarr:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Sonarr
          gethomepage.dev/icon: sonarr
          gethomepage.dev/description: TV Show organizer & manager
          gethomepage.dev/group: Media
          gethomepage.dev/widget.type: sonarr
          gethomepage.dev/widget.url: https://{{ .Release.Name }}.${CLUSTER_DOMAIN}
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_SONARR_API_KEY}}` }}"
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
        parentRefs:
          - name: traefik-gateway
            namespace: network
            sectionName: websecure
