---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret zigbee2mqtt-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
  data:
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
      remoteRef:
        key: zigbee2mqtt
        property: NETWORK_KEY
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
      remoteRef:
        key: zigbee2mqtt
        property: PAN_ID
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID
      remoteRef:
        key: zigbee2mqtt
        property: EXT_PAN_ID
    - secretKey: ZIGBEE2MQTT_CONFIG_MQTT_USER
      remoteRef:
        key: mosquitto/users/zigbee2mqtt
        property: USERNAME
    - secretKey: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
      remoteRef:
        key: mosquitto/users/zigbee2mqtt
        property: PASSWORD
