---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      prowlarr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 6010
            runAsGroup: 6010
            fsGroup: 6010
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.3.1.5238@sha256:4394dff2311238bf5c31e006872122ed4e5f6bf042d33528d80acd44a09c57f7
            env:
              # See: https://wiki.servarr.com/prowlarr/environment-variables
              TZ: ${TIME_ZONE}
              PROWLARR__APP__INSTANCENAME: Prowlarr
              PROWLARR__APP__THEME: dark
              PROWLARR__LOG__LEVEL: info
              PROWLARR__LOG__ANALYTICSENABLED: false
              PROWLARR__SERVER__PORT: &port 8080
              PROWLARR__UPDATE__BRANCH: develop
            # envFrom:
            #   - secretRef:
            #       name: prowlarr-secret
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
              readiness: *probe
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        existingClaim: prowlarr-config
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
            subPath: logs
          - path: /tmp
            subPath: tmp
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Prowlarr
          gethomepage.dev/icon: prowlarr
          gethomepage.dev/description: The ultimate indexer manager
          gethomepage.dev/group: Media
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
