---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      prowlarr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 6010
            runAsGroup: 6010
            fsGroup: 6010
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.1.5.5216@sha256:affb671fa367f4b7029d58f4b7d04e194e887ed6af1cf5a678f3c7aca5caf6ca
            env:
              PROWLARR__APP__INSTANCENAME: Prowlarr
              PROWLARR__APP__THEME: dark
              PROWLARR__LOG__LEVEL: info
              PROWLARR__SERVER__PORT: &port 8080
              PROWLARR__UPDATE__BRANCH: develop
              TZ: ${TIME_ZONE}
            envFrom:
              - secretRef:
                  name: prowlarr-secret
            probes:
              startup: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
              readiness: *probe
              liveness: *probe
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        existingClaim: prowlarr-config
      tmpfs:
        type: emptyDir
        advancedMounts:
          prowlarr:
            app:
              - path: /config/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
    service:
      app:
        ports:
          http:
            port: *port
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Prowlarr
          gethomepage.dev/icon: prowlarr
          gethomepage.dev/description: The ultimate indexer manager
          gethomepage.dev/group: Media
        hosts:
          - host: &domain prowlarr.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *domain
            secretName: prowlarr-tls
