---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app homepage
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: traefik
    - name: cert-manager
    - name: reloader
  path: /apps/selfhosted/homepage/app
  interval: 30m
  prune: true
  targetNamespace: selfhosted
  sourceRef:
    kind: GitRepository
    name: flux-system
