---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret jellyfin-sso
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SSO-Auth.xml: |
          <?xml version="1.0" encoding="utf-8"?>
          <PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <SamlConfigs />
            <OidConfigs>
              <item>
                <key>
                  <string>authelia</string>
                </key>
                <value>
                  <PluginConfiguration>
                    <OidEndpoint>https://authelia.${CLUSTER_DOMAIN}</OidEndpoint>
                    <OidClientId>jellyfin</OidClientId>
                    <OidSecret>{{ .AUTHELIA_JELLYFIN_OIDC_CLIENT_SECRET }}</OidSecret>
                    <Enabled>true</Enabled>
                    <EnableAuthorization>true</EnableAuthorization>
                    <EnableAllFolders>true</EnableAllFolders>
                    <EnabledFolders />
                    <AdminRoles>
                      <string>id_admin</string>
                    </AdminRoles>
                    <Roles>
                      <string>id_admin</string>
                      <string>id_user</string>
                    </Roles>
                    <EnableFolderRoles>false</EnableFolderRoles>
                    <EnableLiveTvRoles>false</EnableLiveTvRoles>
                    <EnableLiveTv>false</EnableLiveTv>
                    <EnableLiveTvManagement>false</EnableLiveTvManagement>
                    <LiveTvRoles />
                    <LiveTvManagementRoles />
                    <FolderRoleMappings />
                    <RoleClaim>groups</RoleClaim>
                    <OidScopes>
                      <string>groups</string>
                    </OidScopes>
                    <CanonicalLinks></CanonicalLinks>
                    <DisableHttps>false</DisableHttps>
                    <SchemeOverride>https</SchemeOverride>
                    <DoNotValidateEndpoints>false</DoNotValidateEndpoints>
                    <DoNotValidateIssuerName>false</DoNotValidateIssuerName>
                    <!-- Fix for issue with Authelia.

                    See: https://github.com/9p4/jellyfin-plugin-sso/issues/305
                    -->
                    <DisablePushedAuthorization>true</DisablePushedAuthorization>
                  </PluginConfiguration>
                </value>
              </item>
            </OidConfigs>
          </PluginConfiguration>
  dataFrom:
    - extract:
        key: JELLYFIN
