---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.3@sha256:fab30d85f4ec3e19556ca1d91b82b12329fc4a6d2a4b330673354af9218e1d28
            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                # memory: 6Gi
                squat.ai/dma-heap: "1"
                squat.ai/dri: "1"
                squat.ai/mali0: "1"
                squat.ai/mpp-service: "1"
                squat.ai/rga: "1"
    service:
      app:
        ports:
          http:
            port: 8096
          # discovery:
          #   port: 7359
          #   protocol: UDP
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Jellyfin
          gethomepage.dev/icon: jellyfin
          gethomepage.dev/description: Open-source Media Server
          gethomepage.dev/group: Media
        hosts:
          - host: &host jellyfin.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: jellyfin-tls
    persistence:
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
      config:
        existingClaim: jellyfin-config
        advancedMounts:
          jellyfin:
            app:
              - path: /config
      media:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/media
        advancedMounts:
          jellyfin:
            app:
              - path: /media
