---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authelia-oidc-cert
spec:
  secretName: authelia-oidc-tls
  commonName: &domain oidc.authelia.${CLUSTER_DOMAIN}
  dnsNames:
    - *domain
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
