---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret authelia-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        authentication.ldap.password.txt: '{{ .AUTHELIA_LDAP_BIND_PASSWORD }}'
        identity_providers.oidc.hmac_secret: '{{ .AUTHELIA_OIDC_HMAC_SECRET }}'
        identity_validation.reset_password.jwt.hmac.key: '{{ .AUTHELIA_RESET_PASSWORD_JWT_KEY }}'
        session.encryption.key: '{{ .AUTHELIA_SESSION_ENCRYPTION_KEY }}'
        storage.encryption.key: '{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}'
  dataFrom:
    - extract:
        key: AUTHELIA
    - extract:
        key: LLDAP
