---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      authelia:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/authelia/authelia
              tag: 4.39.15@sha256:d23ee3c721d465b4749cc58541cda4aebe5aa6f19d7b5ce0afebb44ebee69591
            envFrom:
              - secretRef:
                  name: authelia-secret
            env:
              X_AUTHELIA_CONFIG: /config/configuration.yaml
              X_AUTHELIA_CONFIG_FILTERS: template
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 50Mi
              limits:
                memory: 500Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: authelia
        ports:
          http:
            port: 9091
            protocol: HTTP
          metrics:
            port: 9959
            protocol: HTTP
    serviceMonitor:
      app:
        serviceName: authelia
        endpoints:
          - port: metrics
            path: /metrics
    persistence:
      data:
        existingClaim: authelia-data
      config:
        type: configMap
        name: authelia-config
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
      secret-files:
        type: secret
        name: authelia-secret-files
        globalMounts:
          - path: /secrets
      oidc-cert:
        type: secret
        name: authelia-oidc-tls
        globalMounts:
          - path: /secrets/oidc
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Authelia
          gethomepage.dev/icon: authelia
          gethomepage.dev/description: Open-source authentication and authorization server
          gethomepage.dev/group: Auth
        hosts:
          - host: &host authelia.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: authelia-tls
