---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - externalsecret.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: authelia-config
    files:
      - ./config/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
