---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  path: /apps/observability/kube-prometheus-stack/app
  dependsOn:
    - name: prometheus-operator-crds
    # TODO: when grafana is seperate app, move these deps
    - name: cert-manager
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  timeout: 5m
  wait: true
  prune: true
