---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret renovate-operator-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
  data:
    - secretKey: client-secret
      remoteRef:
        key: AUTHELIA_RENOVATE_OPERATOR_OIDC_CLIENT_SECRET
