---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          dnsConfig:
            options:
              - name: ndots
                value: "1"
          securityContext:
            runAsUser: 13001
            runAsGroup: 13001
            fsGroup: 13001
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            dependsOn:
              - gluetun
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.2@sha256:31ac39705e31f7cdcc04dc46c1c0b0cdf8dc6f9865d4894efc097a33adc41524
            env:
              TZ: ${TIME_ZONE}
              QBT_WEBUI_PORT: &port 8080
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
          # exporter:
          #   image:
          #     repository: ghcr.io/esanchezm/prometheus-qbittorrent-exporter
          #     tag: v1.6.0@sha256:b987d19693a5b2fe7314b22009c6302e084ec801fcf96afaf14065b4cdafc842
          #   env:
          #     QBITTORRENT_HOST: localhost
          #     QBITTORRENT_PORT: *appport
          #     EXPORTER_PORT: &metricsport 17871
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
            env:
              TZ: ${TIME_ZONE}
              # STORAGE_FILEPATH: /tmp/servers.json
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              VPN_SERVICE_PROVIDER: protonvpn
              SERVER_COUNTRIES: Netherlands
              PORT_FORWARD_ONLY: "on"
              VPN_PORT_FORWARDING: "on"
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              VPN_PORT_FORWARDING_UP_COMMAND: >-
                /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{"{{"}}PORTS{{"}}"}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
              FIREWALL_INPUT_PORTS: *port
              FIREWALL_OUTBOUND_SUBNETS: ${LAN_CIDR},${LAN_CIDRv6},${CLUSTER_CIDR},${CLUSTER_CIDRv6},${SERVICE_CIDR}
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            probes:
              startup: &gluetunProbe
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /gluetun-entrypoint
                      - healthcheck
                  periodSeconds: 60
                  timeoutSeconds: 5
                  failureThreshold: 5
              liveness: *gluetunProbe
              readiness: *gluetunProbe
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false  # See: https://github.com/qdm12/gluetun/discussions/2797
              seccompProfile:
                type: Unconfined
              capabilities:
                # drop:
                #   - ALL
                add:
                  - NET_ADMIN
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
            protocol: HTTP
          # metrics:
          #   port: *metricsport
          #   type: HTTP
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: qBittorrent
          gethomepage.dev/icon: qbittorrent
          gethomepage.dev/description: Lightweight, open-source bittorrent client
          gethomepage.dev/group: Media
        hosts:
          - host: &domain qbittorrent.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *domain
            secretName: qbittorrent-tls

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: longhorn-backup
        accessMode: ReadWriteOnce
        size: 512Mi
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      downloads:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/shared/Downloads
        advancedMounts:
          qbittorrent:
            app:
              - path: /config/Downloads
