---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        initContainers:
          coredns:
            image:
              repository: mirror.gcr.io/coredns/coredns
              tag: 1.12.4@sha256:986f04c2e15e147d00bdd51e8c51bcef3644b13ff806be7d2ff1b261d6dfbae1
            args: ["-conf", "/etc/coredns/Corefile"]
            restartPolicy: Always
          gluetun:
            dependsOn: coredns
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
            restartPolicy: Always
            lifecycle:
              postStart:
                exec:
                  # See: https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/kubernetes.md#adding-ipv6-rule--file-exists
                  command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true"]
            env:
              TZ: ${TIME_ZONE}
              PUID: 6001
              GUID: 6001
              DOT: "off"
              DNS_ADDRESS: 127.0.0.2
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              VPN_SERVICE_PROVIDER: custom
              # SERVER_COUNTRIES: Netherlands
              # PORT_FORWARD_ONLY: "on"
              VPN_PORT_FORWARDING: "on"
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              VPN_PORT_FORWARDING_UP_COMMAND: >-
                /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{"{{"}}PORTS{{"}}"}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
              VPN_PORT_FORWARDING_STATUS_FILE: /gluetun/forwarded_port
              PUBLICIP_FILE: /gluetun/ip
              # UPDATER_PERIOD: 24h  # Broken, see: https://github.com/qdm12/gluetun/issues/2820
              FIREWALL_INPUT_PORTS: &port 8080
              FIREWALL_OUTBOUND_SUBNETS: ${LAN_CIDR},${LAN_CIDRv6},${CLUSTER_CIDR},${CLUSTER_CIDRv6},${SERVICE_CIDR}
              WIREGUARD_MTU: 1420
            envFrom:
              - secretRef:
                  name: gluetun-secret
            probes:
              startup: &gluetunProbe
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /gluetun-entrypoint
                      - healthcheck
                  initialDelaySeconds: 15
                  periodSeconds: 60
                  timeoutSeconds: 5
                  failureThreshold: 6
              liveness: *gluetunProbe
              readiness: *gluetunProbe
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
                squat.ai/tun: "1"
            securityContext:
              runAsUser: 0  # needed for iptables
              runAsGroup: 6001
              fsGroup: 6001
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false  # See: https://github.com/qdm12/gluetun/discussions/2797
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - NET_ADMIN
                  - SYS_MODULE  # Kernel space Wireguard
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.2@sha256:31ac39705e31f7cdcc04dc46c1c0b0cdf8dc6f9865d4894efc097a33adc41524
            env:
              TZ: ${TIME_ZONE}
              UMASK: "022"
              QBT_WEBUI_PORT: *port
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              runAsNonRoot: true
              runAsUser: 6000
              runAsGroup: 65537
              fsGroup: 65537
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
          # exporter:
          #   image:
          #     repository: ghcr.io/esanchezm/prometheus-qbittorrent-exporter
          #     tag: v1.6.0@sha256:b987d19693a5b2fe7314b22009c6302e084ec801fcf96afaf14065b4cdafc842
          #   env:
          #     QBITTORRENT_HOST: localhost
          #     QBITTORRENT_PORT: *appport
          #     EXPORTER_PORT: &metricsport 17871
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
            protocol: HTTP
          # metrics:
          #   port: *metricsport
          #   protocol: HTTP
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.middlewares: traefik-auth-chain@kubernetescrd
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: qBittorrent
          gethomepage.dev/icon: qbittorrent
          gethomepage.dev/description: Lightweight, open-source bittorrent client
          gethomepage.dev/group: Media
        hosts:
          - host: &domain qbittorrent.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *domain
            secretName: qbittorrent-tls
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: qbittorrent-config
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      downloads:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/shared/Downloads
        advancedMounts:
          qbittorrent:
            app:
              - path: /downloads
      coredns:
        type: configMap
        name: qbittorrent-coredns
        advancedMounts:
          qbittorrent:
            coredns:
              - path: /etc/coredns/Corefile
                subPath: Corefile
      gluetun:
        type: persistentVolumeClaim
        existingClaim: gluetun-data
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: /gluetun
      # Kernel space Wireguard
      # See: https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/wireguard.md
      modules:
        type: hostPath
        hostPath: /lib/modules
        hostPathType: Directory
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: /lib/modules
                readOnly: true
