---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-database
spec:
  name: app
  owner: app
  cluster:
    name: immich-cnpg-v2
  extensions:
    - ensure: present
      name: vector
    - ensure: present
      name: vchord
      version: 0.5.3
    - ensure: present
      name: cube
    - ensure: present
      name: earthdistance
