---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: habitica
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  values:
    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      habitica:
        strategy: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
        # annotations:
        #   reloader.stakater.com/auto: "true"
        containers:
          habitica:
            image:
              repository: docker.io/awinterstein/habitica-server
              tag: 5.48.0@sha256:c3732b25863f0d0a8f0b11e7cc147a4b7226fe966e4bc3feb426e07a3e256f51
            env:
              TZ: ${TIME_ZONE}
              NODE_DB_URI:
                valueFrom:
                  secretKeyRef:
                    name: habitica-mongodb-secret
                    key: uri
              BASE_URL: https://habitica.${CLUSTER_DOMAIN}
              INVITE_ONLY: true
              EMAIL_SERVER_URL: maddy.default.svc.cluster.local
              EMAIL_SERVER_PORT: 2525
              ADMIN_EMAIL: noreply@mail.${CLUSTER_DOMAIN}
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: &habiticaPort 3000
                    path: /api/v3/status
              readiness: *probe
            # resources:
            #   requests:
            #     cpu: 25m
            #     memory: 64Mi
            #   limits:
            #     memory: 256Mi
            securityContext:
              runAsUser: 0
              # allowPrivilegeEscalation: false
              # readOnlyRootFilesystem: true
              # capabilities:
              #   drop:
              #     - ALL
      # habitica-tmp:
      #   type: emptyDir
      #   advancedMounts:
      #     habitica:
      #       habitica:
      #         - path: /tmp
      # mongodb-tmp:
      #   type: emptyDir
      #   advancedMounts:
      #     mongodb:
      #       mongodb:
      #         - path: /tmp
    service:
      habitica:
        controller: habitica
        ports:
          http:
            port: *habiticaPort
            protocol: HTTP
    route:
      habitica:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Habitica
          gethomepage.dev/icon: habitica
          gethomepage.dev/description: Habit tracker app which treats your goals like an RPG
          gethomepage.dev/group: Apps
          gethomepage.dev/pod-selector: app.kubernetes.io/name = habitica
        hostnames:
          - habitica.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: habitica
        parentRefs:
          - name: traefik-gateway
            namespace: network
            sectionName: websecure
