---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blocky
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
    - name: metallb
    - name: dragonfly-cluster
  path: /apps/blocky/blocky/app
  interval: 30m
  prune: true
  targetNamespace: blocky
  sourceRef:
    kind: GitRepository
    name: flux-system
