---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
    - name: cert-manager
  path: /apps/database/emqx-operator/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: database
  interval: 30m
  timeout: 5m
  wait: true
  prune: true
