---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.8.3@sha256:7ef14f513e487add292b43306cccb4f1cd9dbcbd5eaf85d6438f98b197f930a4
            env:
              VENV_FOLDER: /config/.venv
            resources:
              requests:
                cpu: 50m
                memory: 750Mi
              limits:
                memory: 1.5Gi
            securityContext: &containerSecurity
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.103.1@sha256:fc1d8a57dc5ca5fab67999416165d994ab78a7338b046c4b29f168033a6b7b38
            args:
              - --auth
              - none
              - --disable-telemetry
              - --disable-update-check
              - --user-data-dir
              - /config/.code-server
              - --extensions-dir
              - /config/.code-server
              - --port
              - "12321"
              - /config
            env:
              HASS_SERVER: http://localhost:8123
              HASS_TOKEN:
                secretKeyRef:
                  name: home-assistant-secret
                  key: vscode_token
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            securityContext: *containerSecurity
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        primary: true
        ports:
          http:
            port: 8123
      code-server:
        ports:
          code-server:
            port: 12321
    persistence:
      config:
        existingClaim: home-assistant-config
        globalMounts:
          - path: /config
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: home-assistant-tmp
            code-server:
              - path: /tmp
                subPath: code-server-tmp
              - path: /nonexistent
                subPath: nonexistent
    ingress:
      app:
        className: traefik
        annotations:
          kubernetes.io/tls-acme: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Home Assistant
          gethomepage.dev/icon: home-assistant
          gethomepage.dev/description: Local smart home control and automation
          gethomepage.dev/group: Home Automation
        hosts:
          - host: &host homeassistant.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: ha.${CLUSTER_DOMAIN}  # TODO: remove alias
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
              - ha.${CLUSTER_DOMAIN}  # TODO: remove alias
            secretName: home-assistant-tls
      code-server:
        className: traefik
        annotations:
          kubernetes.io/tls-acme: "true"
          traefik.ingress.kubernetes.io/router.middlewares: auth-forwardauth-authelia@kubernetescrd
        hosts:
          - host: &host code.homeassistant.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: code-server
                  port: code-server
        tls:
          - hosts:
              - *host
            secretName: code-server-tls
