---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 12000
            runAsGroup: 12000
            fsGroup: 12000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.1.3@sha256:9f094e0531e5784d1df9bcb817d95830d1da9d4a03c914f8fd1b3cc6168c4e65
            env:
              VENV_FOLDER: /config/.venv
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.108.1@sha256:867b9a9dedd68f1b46e308cad9525e419db7b0ce0c83831f6a350f37ee7ff6fd
            args:
              - --auth
              - none
              - --disable-telemetry
              - --disable-update-check
              - --config
              - /config/.code-server/config
              - --user-data-dir
              - /config/.code-server/user-data
              - --extensions-dir
              - /config/.code-server/extensions
              - --port
              - "12321"
              - /config
            env:
              HOME: /config/.code-server
              HASS_SERVER: http://localhost:8123
            envFrom:
              - secretRef:
                  name: home-assistant-code-server-secret
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        existingClaim: home-assistant-config
        globalMounts:
          - path: /config
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: home-assistant-tmp
            code-server:
              - path: /tmp
                subPath: code-server-tmp
              - path: /nonexistent
                subPath: nonexistent
    service:
      app:
        primary: true
        ports:
          http:
            port: 8123
            protocol: HTTP
      code-server:
        ports:
          http:
            port: 12321
            protocol: HTTP
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Home Assistant
          gethomepage.dev/icon: home-assistant
          gethomepage.dev/description: Local smart home control and automation
          gethomepage.dev/group: Home Automation
          gethomepage.dev/app: home-assistant
        hostnames:
          - &host homeassistant.${CLUSTER_DOMAIN}
        rules:
          - backendRefs:
              - identifier: app
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
      code-server:
        hostnames:
          - *host
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /code/
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: auth-chain
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /
            backendRefs:
              - identifier: code-server
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
