---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: falco
  values: # https://github.com/falcosecurity/charts/blob/master/charts/falco/values.yaml
    collectors:
      containerEngine:
        engines:
          docker:
            enabled: false
          podman:
            enabled: false
          containerd:
            enabled: true
            sockets:
              - /run/k3s/containerd/containerd.sock
          lxc:
            enabled: false
          libvirt_lxc:
            enabled: false
          bpm:
            enabled: false
      kubernetes:
        enabled: true
    falcosidekick:
      enabled: true
      replicaCount: 1
      config:
        alertmanager:
          hostport: http://vmalertmanager-victoria-metrics.observability.svc.cluster.local:9093
      serviceMonitor:
        enabled: true
      prometheusRules:
        enabled: true
      grafana:
        dashboards:
          enabled: true
      webui:
        enabled: true
        replicaCount: 1
    metrics:
      enabled: true
    serviceMonitor:
      create: true
