# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.2-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: openbao-secrets
stringData:
  unseal-20260606-1.key: ENC[AES256_GCM,data:D0vS69hvfMc3CLBFIZuKK9VWP7UnfSogHUWKltrLDvVOXav843p/bBEG6oY=,iv:soI69bAq7TAXtxQOcUetuZpb53kW8yMKU6td+/fes+A=,tag:96V28kn5FfiLytu55NlslQ==,type:str]
sops:
  age:
    - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRFZhVlZWRXRpQzJOZzB4
        RHI2RkE0SmtVZ1BYUjVpMzA5ZFVjb0ZheEZJCkc1cGx2TTdqSHoxRkROWXpvdytY
        NER5OEhMTG1OYS9YZFc1VXhFZTZzT28KLS0tIHFDL01yWnNjZWUzN2VZeG1vYVRm
        NWU3ai9PQzhHN1pJMGJKeFdxbkdmenMKlNSTiyyZLDf0WgnRxOiHibjF46LkduFw
        Bq8doPOiEZOB+dmiTU1lkv6vUkzBE3JrSCODSe1puKRKW/G94mhgag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T13:02:50Z"
  mac: ENC[AES256_GCM,data:KGrvB295vYDt/ugUdqgS8YNpfYQh9IdEM5KcENUq4omW1xMWLOnXqINHIDh5qixMIJ3AHWJ5z4oYH3stM1osl2IXFezv8ECswB4+dUE7AjJFEHF5uOtB1mV817ukeP1hachpmrsjU1HTzq5pbufcYGSDwY8Bi4ymHLkA9AS0da8=,iv:9q1AMn/N2XAmlYOVWjkGmOXzXDJAIwRSZOS9T/iJIRE=,tag:+JZ8LVojlSJYefiM4L+IkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.2-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: openbao-auth-lldap
stringData:
  bind-password: ENC[AES256_GCM,data:nJX+biGx1xneSK2plZ+AdYF/IbutdF7YOpGSp/sXhmfCC15u81PmZfwelktSgaOQ,iv:x/y6b5QV2Nrg3SPpahK0/1R9xGcqzesQ41xEyUgM3mQ=,tag:F/IqVzYnaaO70aJndPKSgA==,type:str]
sops:
  age:
    - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRFZhVlZWRXRpQzJOZzB4
        RHI2RkE0SmtVZ1BYUjVpMzA5ZFVjb0ZheEZJCkc1cGx2TTdqSHoxRkROWXpvdytY
        NER5OEhMTG1OYS9YZFc1VXhFZTZzT28KLS0tIHFDL01yWnNjZWUzN2VZeG1vYVRm
        NWU3ai9PQzhHN1pJMGJKeFdxbkdmenMKlNSTiyyZLDf0WgnRxOiHibjF46LkduFw
        Bq8doPOiEZOB+dmiTU1lkv6vUkzBE3JrSCODSe1puKRKW/G94mhgag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T13:02:50Z"
  mac: ENC[AES256_GCM,data:KGrvB295vYDt/ugUdqgS8YNpfYQh9IdEM5KcENUq4omW1xMWLOnXqINHIDh5qixMIJ3AHWJ5z4oYH3stM1osl2IXFezv8ECswB4+dUE7AjJFEHF5uOtB1mV817ukeP1hachpmrsjU1HTzq5pbufcYGSDwY8Bi4ymHLkA9AS0da8=,iv:9q1AMn/N2XAmlYOVWjkGmOXzXDJAIwRSZOS9T/iJIRE=,tag:+JZ8LVojlSJYefiM4L+IkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
