# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.1-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: openbao-secrets
stringData:
  unseal-20260606-1.key: ENC[AES256_GCM,data:D0vS69hvfMc3CLBFIZuKK9VWP7UnfSogHUWKltrLDvVOXav843p/bBEG6oY=,iv:soI69bAq7TAXtxQOcUetuZpb53kW8yMKU6td+/fes+A=,tag:96V28kn5FfiLytu55NlslQ==,type:str]
sops:
  age:
    - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRFZhVlZWRXRpQzJOZzB4
        RHI2RkE0SmtVZ1BYUjVpMzA5ZFVjb0ZheEZJCkc1cGx2TTdqSHoxRkROWXpvdytY
        NER5OEhMTG1OYS9YZFc1VXhFZTZzT28KLS0tIHFDL01yWnNjZWUzN2VZeG1vYVRm
        NWU3ai9PQzhHN1pJMGJKeFdxbkdmenMKlNSTiyyZLDf0WgnRxOiHibjF46LkduFw
        Bq8doPOiEZOB+dmiTU1lkv6vUkzBE3JrSCODSe1puKRKW/G94mhgag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T08:04:13Z"
  mac: ENC[AES256_GCM,data:9CBMRHoktY7KpHwRqa0Pan8DUL7OwJT5UAbRTLhk4cMLZI56YKcxDybdlwgYqXdwb7ED4/ruqXMBrhLhMzZTthDlBXC8vQh7tXysT5E8MLdGsREl3GMHc0z8ssaiR88ZJv14OdpXOVPEti/NkEQ6WVWm4HiX/+4CvArEUYLpgFY=,iv:twpOdJMrGXA9iQdRNRUZSEKBGUTRC+a5H2zmiIWHr1Y=,tag:nK4BlPuL0KMLFsdt42ssSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
