# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.1-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: openbao-secrets
stringData:
  unseal-20260606-1.key: ENC[AES256_GCM,data:tcgQPLSAlY5MGs8/WgNkyWD5FT0uVlDndVh1IopC20372sjKw/Wz7HlApmtFeSDDpo1rLxgRrqDq+duHf6GsyTnLamITqR1XBmYVms53SgD2tyCybZ8=,iv:EaEBS3gN8DKRMz9Kz0HTD7hIZpY5aEUq/vWso+vnsso=,tag:oEpyxghRwgewDDE0B61gGg==,type:str]
sops:
  age:
    - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSDF5djlrQ1dHRmc5Qkd1
        RldqaG51ZXF2azh0emVMODVsdm1Zay96eFJNCnNHK0xwcWlMTXppUldzbyt2akpv
        OEh3TnpDUW5RMVo5ZlVweHNZZlR0WEUKLS0tIE9LbnNmS2VSWFgwaGd5aVFCcHBH
        Y0xnYWtGMGp1MmJFdUVUMXFZUWRGWXcKy0v9UDtY/z5VGEohNdQ1cDfAVEPJid9t
        NHnysb+R4KPJMK7QWQkAKc4sFYOboYsnAf+gwwLYJYPYeMueBKaasw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-05T22:04:25Z"
  mac: ENC[AES256_GCM,data:8p8yCg34Ocj6+VBIeVqzyBOE82kWhV0EcAAYNssAvLNT/V3kOtxikqzudYjx56FkLJOKqg1eBNh/68GiFqt0A+ZhQm/2IoTdt4/z9E9n8AsVFEOFOUsd0DCeEtb6yXsTCKegbFkxNgpFYB7gulDULAzVruSoKuITQybBYPjLuNw=,iv:FhxIkxY0+3r2Hn571Heet0MvhYJeZL6nXTmY1y1/Iqw=,tag:zKS6RgAQCDt4BV1G42B4+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
