---
# yaml-language-server: $schema=https://0xerr0r.github.io/blocky/v0.33.0/config.schema.json
ports:
  dns: 1053
  http: 4000
redis:
  address: blocky-dragonfly.network.svc.cluster.local:6379
  password: "{{ .DRAGONFLY_PASSWORD }}"
prometheus:
  enable: true
upstreams:
  groups:
    default:
      - &quad9_tls tcp-tls:dns.quad9.net
      - &dns4eu_tls tcp-tls:unfiltered.joindns4.eu
bootstrapDns:
  - upstream: *quad9_tls
    ips:
      - 9.9.9.9
      - 149.112.112.112
      - 2620:fe::fe
      - 2620:fe::9
  - upstream: *dns4eu_tls
    ips:
      - 86.54.11.100
      - 86.54.11.200
      - 2a13:1001::86:54:11:100
      - 2a13:1001::86:54:11:200
conditional:
  fallbackUpstream: false
  mapping:
    fritz.box: ${FRITZBOX_IP}
    178.168.192.in-addr.arpa: ${FRITZBOX_IP}
clientLookup:
  upstream: ${FRITZBOX_IP}
customDNS:
  mapping:
    nas.${CLUSTER_DOMAIN}: ${NAS_IP}
    bao.${CLUSTER_DOMAIN}: ${OPENBAO_IP},${OPENBAO_IPv6}
    ${CLUSTER_DOMAIN}: "${PROXY_IP},${PROXY_IPv6}"
blocking:
  denylists:
    ads:
      - https://big.oisd.nl/domainswild
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/normal.txt
    malware:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt
  clientGroupsBlock:
    default:
      - ads
      - malware
  loading:
    downloads:
      cachePath: /var/cache/blocky/lists
