---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/longhorn.io/recurringjob_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot
spec:
  cron: "*/15 * * * *"
  task: "snapshot"
  groups:
    - backup
  retain: 24
  concurrency: 3
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/longhorn.io/recurringjob_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup
spec:
  cron: "0 0 * * *"
  task: "backup"
  groups:
    - backup
  retain: 7
  concurrency: 3
  parameters:
    full-backup-interval: "7"
