---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/storageclass-storage-v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-backup
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  recurringJobSelector: |
    [
      {
        "name":"backup",
        "isGroup":true
      }
    ]
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/storageclass-storage-v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-backup-high-io
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  recurringJobSelector: |
    [
      {
        "name":"backup",
        "isGroup":true
      }
    ]
