---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs-single
  interval: 30m
  driftDetection:
    mode: enabled
  values: # https://docs.victoriametrics.com/helm/victoria-logs-single/#parameters
    fullnameOverride: victoria-logs
    server:
      retentionPeriod: 10d
      persistentVolume:
        enabled: true
        storageClassName: longhorn-victoria-metrics
        size: 20Gi
      route:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Victoria Logs
          gethomepage.dev/icon: victorialogs
          gethomepage.dev/description: Simple & Reliable Logs Solution
          gethomepage.dev/group: Observability
          gethomepage.dev/pod-selector: app.kubernetes.io/name=victoria-logs-single
        hostnames:
          - victoria-logs.${CLUSTER_DOMAIN}
        extraRules:
          - filters:
              - type: RequestRedirect
                requestRedirect:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /select/vmui/
                  statusCode: 302
            matches:
              - path:
                  type: Exact
                  value: /
        parentRefs:
          - name: traefik-gateway
            namespace: network
            sectionName: websecure
      vmServiceScrape:
        enabled: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: observability
      labels:
        grafana_dashboard: "1"
