---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ring-mqtt
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      ring-mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              # See: https://github.com/just-containers/s6-overlay/issues/600
              S6_READ_ONLY_ROOT: 1
              S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: 1
            image:
              repository: tsightler/ring-mqtt
              tag: 5.9.1@sha256:b1c45893aee660b45712648d4c48d5891da8fbd04682fde9c826e58fde9612cb
            ports:
              - name: rtsp
                containerPort: &port 8554
                protocol: TCP
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 12004
        runAsGroup: 12004
        fsGroup: 12004
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    persistence:
      data:
        existingClaim: ring-mqtt-data
        advancedMounts:
          ring-mqtt:
            app:
              - path: /data
      config:
        type: secret
        name: ring-mqtt-config
        advancedMounts:
          ring-mqtt:
            app:
              - path: /data/config.json
                subPath: config.json
                readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          ring-mqtt:
            app:
              - path: /run
