---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
  path: /apps/tailscale/tailscale-operator/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: tailscale
  prune: true
  interval: 30m
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-router
  namespace: flux-system
spec:
  dependsOn:
    - name: tailscale-operator
  path: /apps/tailscale/tailscale-operator/router
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: &namespace tailscale
  prune: true
  interval: 30m
  timeout: 5m
  healthChecks:
    - apiVersion: tailscale.com/v1alpha1
      kind: Connector
      name: home-lan
      namespace: *namespace
