---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.86.2
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    oauthSecretVolume:
      secret:
        secretName: tailscale-oauth
