---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      garage:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 7000
            runAsGroup: &nfsGroup 65538
            fsGroup: *nfsGroup
          # This is avoid 132 exit code crashes on the RPI4
          # TODO: figure out what CPU instructions are needed
          # and create NFD rule OR wait until RPI4 is retired
          # remove this entirely.
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: NotIn
                        values:
                          - raspberrypi
        containers:
          app:
            image:
              repository: dxflrs/garage
              tag: v2.1.0@sha256:4c9b34c113e61358466e83fd6e7d66e6d18657ede14b776eb78a93ee8da7cf6a
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi
            env:
              TZ: ${TIME_ZONE}
            probes: &probes
              liveness: &probe
                enabled: true
              readiness: *probe
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      webui:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 7001
            runAsGroup: 7001
            fsGroup: 7001
        containers:
          app:
            image:
              repository: khairul169/garage-webui
              tag: 1.1.0@sha256:17c793551873155065bf9a022dabcde874de808a1f26e648d4b82e168806439c
            env:
              TZ: ${TIME_ZONE}
              API_BASE_URL: http://garage:3903
              S3_ENDPOINT_URL: http://garage:3900
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi
            probes: *probes
            securityContext: *securityContext
    persistence:
      config:
        type: secret
        name: garage-secret
        globalMounts:
          - path: /etc/garage.toml
            subPath: garage.toml
      meta:
        type: persistentVolumeClaim
        existingClaim: garage-meta
        advancedMounts:
          garage:
            app:
              - path: /meta
      data:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/garage
        advancedMounts:
          garage:
            app:
              - path: /data
    service:
      garage:
        controller: garage
        ports:
          s3:
            port: 3900
            protocol: HTTP
            primary: true
          api:
            port: 3903
            protocol: HTTP
      webui:
        controller: webui
        ports:
          http:
            port: &port 3909
            protocol: HTTP
    route:
      webui:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Garage
          gethomepage.dev/icon: garage
          gethomepage.dev/description: S3-compatible object store for small self-hosted deployments
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/pod-selector: app.kubernetes.io/name = garage
        hostnames:
          - garage.${CLUSTER_DOMAIN}
        rules:
          - filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: auth-chain
            backendRefs:
              - name: garage-webui
                port: *port
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
            sectionName: websecure
