---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      immich-machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            # TODO: Once I got Talos and the RKNPU working, make this better
            # Probably want to use the generic-device-plugin at that point
            feature.node.kubernetes.io/cpu-model.family: "79"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.2.0@sha256:5df77af74af072f1552720d72f1838f63a60d7173d4187ab014686ccd18b567e
            resources:
              requests:
                cpu: 15m
                memory: 250Mi
              limits:
                memory: 4000Mi
            probes:
              startup:
                enabled: true
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              DB_USERNAME:
                secretKeyRef:
                  name: immich-cloudnative-pg-app
                  key: username
              DB_PASSWORD:
                secretKeyRef:
                  name: immich-cloudnative-pg-app
                  key: password
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-config
              - configMapRef:
                  name: immich-machine-learning-config
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3003
    persistence:
      library:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/immich
        advancedMounts:
          immich-machine-learning:
            app:
              - path: /usr/src/app/upload
      cache:
        type: emptyDir
