---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-machine-learning
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      immich-machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            # TODO: Once I get Talos and the RKNPU working, make this better
            # Probably want to use the generic-device-plugin at that point
            feature.node.kubernetes.io/cpu-model.family: "47"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.4.1@sha256:b3deefd1826f113824e9d7bc30d905e7f823535887d03f869330946b6db3b44a
            env:
              DB_USERNAME:
                secretKeyRef:
                  name: immich-cloudnative-pg-app
                  key: username
              DB_PASSWORD:
                secretKeyRef:
                  name: immich-cloudnative-pg-app
                  key: password
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-config
              - configMapRef:
                  name: immich-machine-learning-config
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
            resources:
              requests:
                cpu: 75m
                memory: 1Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      library:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/immich
        globalMounts:
          - path: /usr/src/app/upload
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /cache
            subPath: cache
          - path: /tmp
            subPath: tmp
    service:
      app:
        ports:
          http:
            port: 3003
            protocol: HTTP
