---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mojo2600-pihole-kubernetes
  namespace: flux-system
spec:
  interval: 1h
  url: https://mojo2600.github.io/pihole-kubernetes/
