---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: maddy
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
  path: /apps/default/maddy/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  interval: 30m
  timeout: 3m
  wait: true
  prune: true
  suspend: true
