---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.3.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      zigbee2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 6101
            runAsGroup: 6101
            fsGroup: 6101
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.7.0@sha256:7da30df2c3e53ea02e0bbce0241306358e946b2b5ce6ec02ecdf90be0a96c694
            env:
              TZ: ${TIME_ZONE}
              Z2M_WATCHDOG: default
              ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: 11
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee2mqtt.${CLUSTER_DOMAIN}
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: true
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto:1883
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: false
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: deconz
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2487785-if00
            envFrom:
              - secretRef:
                  name: zigbee2mqtt-secret
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
                squat.ai/conbee2: "1"
            securityContext:
              runAsGroup: 20
              capabilities:
                drop:
                  - ALL
                add:
                  - SYS_RAWIO
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
    service:
      app:
        ports:
          http:
            port: 8080
    persistence:
      data:
        existingClaim: zigbee2mqtt-data
        advancedMounts:
          zigbee2mqtt:
            app:
              - path: /app/data
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.middlewares: traefik-auth-chain@kubernetescrd
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Zigbee2MQTT
          gethomepage.dev/icon: zigbee2mqtt
          gethomepage.dev/description: Bridge Zigbee devices to MQTT
          gethomepage.dev/group: Home Automation
        hosts:
          - host: &host zigbee2mqtt.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: zigbee2mqtt-tls
