---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      zigbee2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 6101
            runAsGroup: 6101
            fsGroup: 6101
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.7.1@sha256:163e7351430a95d550d5b1bb958527edc1eff115eb013ca627f3545a192e853f
            env:
              TZ: ${TIME_ZONE}
              Z2M_WATCHDOG: default
              ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: 11
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee2mqtt.${CLUSTER_DOMAIN}
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: true
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto:1883
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: false
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: deconz
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2487785-if00
            envFrom:
              - secretRef:
                  name: zigbee2mqtt-secret
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
                squat.ai/conbee2: "1"
            securityContext:
              capabilities:
                drop:
                  - ALL
                add:
                  - SYS_RAWIO
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
    persistence:
      data:
        existingClaim: zigbee2mqtt-data
        globalMounts:
          - path: /app/data
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Zigbee2MQTT
          gethomepage.dev/icon: zigbee2mqtt
          gethomepage.dev/description: Bridge Zigbee devices to MQTT
          gethomepage.dev/group: Home Automation
        hostnames:
          - zigbee2mqtt.${CLUSTER_DOMAIN}
        rules:
          - filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: auth-chain
            backendRefs:
              - identifier: app
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
