---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
    - name: traefik
    - name: longhorn
  path: /apps/security/vaultwarden/app
  interval: 15m
  prune: true
  targetNamespace: security
  sourceRef:
    kind: GitRepository
    name: flux-system
