---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-issuers
    - name: traefik
    - name: longhorn-storage
    - name: external-secrets-stores
  path: /apps/security/vaultwarden/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: security
  interval: 30m
  timeout: 5m
  wait: true
  prune: true
