---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret isponsorblocktv-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    template:
        engineVersion: v2
        data:
          config.json: |
            {
                "devices": {{ .ISPONSERBLOCKTV_DEVICES }},
                "apikey": "",
                "skip_categories": [
                    "sponsor",
                    "selfpromo",
                    "exclusive_access",
                    "interaction",
                    "poi_highlight",
                    "intro",
                    "outro",
                    "preview",
                    "filler",
                    "music_offtopic"
                ],
                "channel_whitelist": [],
                "skip_count_tracking": false,
                "mute_ads": true,
                "skip_ads": true
            }
  data:
    - secretKey: ISPONSERBLOCKTV_DEVICES
      remoteRef:
        key: ISPONSERBLOCKTV_DEVICES
