---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      bazarr:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 6040
            runAsGroup: 65537
            fsGroup: 65537
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/bazarr
              tag: 1.5.4@sha256:6e2fab9cca3096714795458aec222da5e2e5cde07ed07e439f9879c9de3b5b94
            env:
              TZ: "${TIME_ZONE}"
              BAZARR__INSTANCE_NAME: "{{ .Release.Name }}"
              BAZARR__PORT: &port 6767
              BAZARR__APPLICATION_URL: "https://{{ .Release.Name }}.${CLUSTER_DOMAIN}"
              BAZARR__LOG_LEVEL: info
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/
                    port: *port
                  initialDelaySeconds: 6
                  timeoutSeconds: 5
              readiness: *probe
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        existingClaim: bazarr-config
      media:
        type: nfs
        server: ${NAS_IP}
        path: /volume1/media
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Bazarr
          gethomepage.dev/icon: bazarr
          gethomepage.dev/description: Subtitle manager
          gethomepage.dev/group: Media
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
