---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  driftDetection:
    mode: enabled
  values:
    controllers:
      homepage:
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          identifier: homepage
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: &nobody 65534
            runAsGroup: *nobody
            fsGroup: *nobody
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.8.0@sha256:7dc099d5c6ec7fc945d858218565925b01ff8a60bcbfda990fc680a8b5cd0b6e
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            env:
              HOMEPAGE_ALLOWED_HOSTS: &host homepage.${CLUSTER_DOMAIN}
              LOG_TARGETS: stdout
              TZ: ${TIME_ZONE}
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: &port 3000
                    path: /api/healthcheck
                    httpHeaders:
                      - name: Host
                        value: *host
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - path: /app/config
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - *host
        rules:
          - backendRefs:
              - identifier: app
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
    serviceAccount:
      homepage: {}
    rbac:
      bindings:
        homepage:
          type: ClusterRoleBinding
          roleRef:
            kind: ClusterRole
            name: homepage
          subjects:
            - identifier: homepage
      roles:
        homepage:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - namespaces
                - pods
                - nodes
              verbs:
                - get
                - list
            - apiGroups:
                - extensions
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - get
                - list
            - apiGroups:
                - traefik.io
              resources:
                - ingressroutes
              verbs:
                - get
                - list
            - apiGroups:
                - gateway.networking.k8s.io
              resources:
                - httproutes
                - gateways
              verbs:
                - get
                - list
            - apiGroups:
                - metrics.k8s.io
              resources:
                - nodes
                - pods
              verbs:
                - get
                - list
