---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      homepage:
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          identifier: homepage
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.7.0@sha256:b6ac42c31845ea7c862d71451c16413a6284430d8ff08e16ad791f42718a7c71
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            env:
              HOMEPAGE_ALLOWED_HOSTS: &host homepage.${CLUSTER_DOMAIN}
              LOG_TARGETS: stdout
              TZ: ${TIME_ZONE}
            # envFrom:
            #   - secretRef:
            #       name: homepage-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: &port 3000
                    path: /api/healthcheck
                    httpHeaders:
                      - name: Host
                        value: *host
                  initialDelaySeconds: 0
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: homepage-tls
    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - path: /app/config
    serviceAccount:
      homepage: {}
    rbac:
      bindings:
        homepage:
          type: ClusterRoleBinding
          roleRef:
            kind: ClusterRole
            name: homepage
          subjects:
            - identifier: homepage
      roles:
        homepage:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - namespaces
                - pods
                - nodes
              verbs:
                - get
                - list
            - apiGroups:
                - extensions
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - get
                - list
            - apiGroups:
                - traefik.io
              resources:
                - ingressroutes
              verbs:
                - get
                - list
            - apiGroups:
                - gateway.networking.k8s.io
              resources:
                - httproutes
                - gateways
              verbs:
                - get
                - list
            - apiGroups:
                - metrics.k8s.io
              resources:
                - nodes
                - pods
              verbs:
                - get
                - list
