---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret blocky-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yml: |
          upstreams:
            groups:
              default:
                - &quad9_tls tcp-tls:dns.quad9.net
          bootstrapDns:
            - upstream: *quad9_tls
              ips:
                - 9.9.9.9
                - 149.112.112.112
                - 2620:fe::fe
                - 2620:fe::9
          conditional:
            fallbackUpstream: false
            mapping:
              fritz.box: 192.168.178.1
              178.168.192.in-addr.arpa: 192.168.178.1
          clientLookup:
            upstream: 192.168.178.1
          blocking:
            denylists:
              ads:
                - https://big.oisd.nl/domainswild
                - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.txt
              malware:
                - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh.txt
                - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt
            clientGroupsBlock:
              default:
                - ads
                - malware
          customDNS:
            mapping:
              ${CLUSTER_DOMAIN}: "${PROXY_IP},${PROXY_IPv6}"
          caching:
            minTime: 15m
            maxTime: 4h
            prefetching: true
            cacheTimeNegative: 15s
          ports:
            http: 4000
          redis:
            address: blocky-dragonfly
            password: "{{ .BLOCKY_DRAGONFLY_PASSWORD }}"
          prometheus:
            enable: true
  dataFrom:
    - extract:
        key: BLOCKY_DRAGONFLY
