---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app blocky
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      blocky:
        replicas: 3
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
        containers:
          app:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.28.2@sha256:5f84a54e4ee950c4ab21db905b7497476ece2f4e1a376d23ab8c4855cabddcba
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /app/blocky
                      - healthcheck
                      - --port
                      - "1053"
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      config:
        type: secret
        name: blocky-config
        globalMounts:
          - path: /app/config.yml
            subPath: config.yml
    service:
      app:
        ports:
          http:
            port: 4000
      dns:
        type: LoadBalancer
        ipFamilyPolicy: RequireDualStack
        annotations:
          metallb.io/loadBalancerIPs: "${DNS_IP},${DNS_IPv6}"
        ports:
          dns-tcp:
            port: 53
            targetPort: 1053
            protocol: TCP
          dns-udp:
            port: 53
            targetPort: 1053
            protocol: UDP
    serviceMonitor:
      app:
        service:
          name: blocky-app
        endpoints:
          - port: http
            path: /metrics
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Blocky
          gethomepage.dev/icon: blocky
          gethomepage.dev/description: DNS proxy and ad-blocker written in Go
          gethomepage.dev/group: Network
        parentRefs:
          - name: traefik-gateway
            namespace: traefik
        hostnames:
          - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
        rules:
          - backendRefs:
              - identifier: app
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: auth-chain
