---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etcd-operator
  namespace: etcd-operator-system
spec:
  interval: 30m
  chart:
    spec:
      chart: etcd-operator
      version: 0.4.2
      sourceRef:
        kind: HelmRepository
        name: aenix-io
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    etcdOperator:
      vpa:
        enabled: false
    kubeRbacProxy:
      vpa:
        enabled: false
