---
extends: default
ignore: |
  *.sops.*
rules:
  # truthy:
  #   allowed-values: ["true", "false", "on"]
  indentation: enable
  line-length: disable
  comments:
    min-spaces-from-content: 2
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
