---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    crds:
      create: true
    monitoring:
      podMonitorEnabled: true
      # grafanaDashboard:
      #   create: true
