---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret maddy-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
  data:
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: maddy/simple-mail-service
        property: USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: maddy/simple-mail-service
        property: PASSWORD
