---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
    - name: generic-device-plugin
    - name: longhorn-storage
  path: /apps/media/qbittorrent/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: media
  prune: true
  interval: 15m
  retryInterval: 2m
  timeout: 3m
  wait: true
