---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: &app dragonfly
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.32.0
  replicas: 2
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: *app
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          # Do not schedule on the Raspberry Pi 4
          # See: https://github.com/dragonflydb/dragonfly/issues/777
          - matchExpressions:
              - key: feature.node.kubernetes.io/cpu-model.id
                operator: NotIn
                values: ["53379"]
