---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
  path: /apps/database/cloudnative-pg/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: database
  interval: 30m
  retryInterval: 3m
  timeout: 5m
  wait: true
  prune: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plugin-barman-cloud
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  path: /apps/database/cloudnative-pg/plugin-barman-cloud
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: database
  interval: 30m
  retryInterval: 3m
  timeout: 5m
  wait: true
  prune: true
