---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 15m
  chart:
    spec:
      chart: external-secrets
      version: 0.19.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:  # Docs: https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
    serviceMonitor:
      enabled: true
