---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret hcpy-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
    template:
      templateFrom:
        - configMap:
            name: hcpy-config-tpl
            items:
              - key: config.ini
              - key: devices.json
  dataFrom:
    - extract:
        key: hcpy/devices
    - extract:
        key: mosquitto/users/hcpy
      rewrite:
        - regexp:
            source: "(.*)"
            target: MQTT_$1
