---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret hass-configurator-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    template:
      templateFrom:
        - configMap:
            name: hass-configurator-config-tpl
            items:
              - key: settings.conf
  data:
    - secretKey: HASS_API_PASSWORD
      remoteRef:
        key: HOME_ASSISTANT_CONFIGURATOR_ACCESS_TOKEN
