---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        session.encryption.key: "{{ .AUTHELIA_SESSION_ENCRYPTION_KEY }}"
        storage.encryption.key: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        identity_validation.reset_password.jwt.hmac.key: "{{ .AUTHELIA_RESET_PASSWORD_JWT_KEY }}"
  dataFrom:
    - extract:
        key: AUTHELIA
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-users
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: authelia-users
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        users_database.yml: "{{ .AUTHELIA_USERS }}"
  data:
    - secretKey: AUTHELIA_USERS
      remoteRef:
        key: AUTHELIA_USERS
