---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/metallb.io/ipaddresspool_v1beta1.json
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
spec:
  addresses:
    - ${LB_IP_POOL}
    - ${LB_IPv6_POOL}
