---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
    - name: cert-manager-issuers
    - name: external-secrets-stores
    - name: traefik
  path: /apps/security/authelia/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: security
  interval: 15m
  timeout: 5m
  wait: true
  prune: true
