# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.1-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: doppler-secret
stringData:
  token: ENC[AES256_GCM,data:3EAfWr1Q7Ea9fghxhUZ15DmS0zkvX0NUXipAWXzSMdMqUS2SGni1Exg7iqXxAFcgjuKiDck=,iv:E+ZceNaGTBbBdHOsNAXY3VEnAZLa+DXYEdqStUnq5JA=,tag:htslpHS/81yenVrh+KJ4Og==,type:str]
sops:
  age:
    - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSDF5djlrQ1dHRmc5Qkd1
        RldqaG51ZXF2azh0emVMODVsdm1Zay96eFJNCnNHK0xwcWlMTXppUldzbyt2akpv
        OEh3TnpDUW5RMVo5ZlVweHNZZlR0WEUKLS0tIE9LbnNmS2VSWFgwaGd5aVFCcHBH
        Y0xnYWtGMGp1MmJFdUVUMXFZUWRGWXcKy0v9UDtY/z5VGEohNdQ1cDfAVEPJid9t
        NHnysb+R4KPJMK7QWQkAKc4sFYOboYsnAf+gwwLYJYPYeMueBKaasw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-25T16:11:05Z"
  mac: ENC[AES256_GCM,data:ohpb4/Trwd/D3SNxe9/l+7EHXJ2nTtpY3CI5LJTtDfUyupBHH7Tz+ZdETczjHLJnuAysxLcWTfM4b+zb0v9ouGKeVfcZYe0L/0kScC+1LaWmClGrYmmmJOYd1ApPAPGqpEmlyUBTk6l3OmbXA1UPvc7NIS2hH5CZwJC3Cp2p080=,iv:yApgCpAZ5rtIK9Fsnd8mzOqn9EaiL1fQD3LAhu5iYyE=,tag:qiggr40hGIBoqdhwI0WUJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
