# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.1-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: doppler-secret
stringData:
  token: ENC[AES256_GCM,data:PSkGLwIAuchstbiYf0tUOYJ5HASUn0BTIrlUns96Sxkh1NeNuEJ443UGiIpYOqcG4bIyYzA=,iv:rQeVnFtERTBXogHefsmoBVpVVZVjYI2nTJ+yGc5klyo=,tag:tkbsJIZr1vRcxLH0X0RhMQ==,type:str]
sops:
  age:
    - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZGVhM2tTUGlhVytoY25t
        cHJuUTBNdk5OVnRJek0xeWR5QlNFQ3dFa2prCmROMzZQNS8xVlYxdmJueHVPUG02
        bFpjWlMvbGxSRGhCcnBjWitpelk3WDAKLS0tIG1INWpMTzJqTDhXOFIyWGEwZ2tp
        T3ppWTFBUHUrNGZqaUFmRWNTUXFabEUK/3wrvn3JoCdvOIBu+468SVpLlLWSU6ju
        Wy0gxYGgGN38cHVU+CDVXeeojWT/sbFaMSUfFoHVytahLn2iqmjCzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T08:06:42Z"
  mac: ENC[AES256_GCM,data:42XYHUJaVMzwClCw+dRe1/nFKUm6tfpdQaM7J82KQ0yjVYEp/BTNt9/pr468E/9gY1TEaet0Z6H9TAPQCHYe3thExno/tTbS6kN5pDmrTX+LuM6tB3+RDBLrHL6qEcbZZCoulte3OV3FQovxjFxPildS0sZLmo2trS1D73pSIzs=,iv:bWifwrErzh2AThxnv75EK5B4R0LUOmJJcafSbOQ66VY=,tag:mLmhigc1P3/4+THfL6oznw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
