---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret mealie-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: authelia/oidc/mealie
        property: CLIENT_SECRET
