---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
  data:
    - secretKey: HOMEPAGE_VAR_IMMICH_API_KEY
      remoteRef:
        key: HOMEPAGE_IMMICH_API_KEY
