---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *secret
  data:
    - secretKey: HOMEPAGE_VAR_BAZARR_API_KEY
      remoteRef:
        key: bazarr
        property: API_KEY
    - secretKey: HOMEPAGE_VAR_IMMICH_API_KEY
      remoteRef:
        key: immich/api/homepage
        property: API_KEY
    - secretKey: HOMEPAGE_VAR_JELLYFIN_API_KEY
      remoteRef:
        key: jellyfin/api/homepage
        property: API_KEY
    - secretKey: HOMEPAGE_VAR_MEALIE_API_TOKEN
      remoteRef:
        key: mealie/api/homepage
        property: API_TOKEN
    - secretKey: HOMEPAGE_VAR_PROWLARR_API_KEY
      remoteRef:
        key: prowlarr
        property: API_KEY
    - secretKey: HOMEPAGE_VAR_QBITTORRENT_WEB_USERNAME
      remoteRef:
        key: qbittorrent
        property: WEB_USERNAME
    - secretKey: HOMEPAGE_VAR_QBITTORRENT_WEB_PASSWORD
      remoteRef:
        key: qbittorrent
        property: WEB_PASSWORD
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: radarr
        property: API_KEY
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: sonarr
        property: API_KEY
