---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret tailscale-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: TAILSCALE_HOME_LAN_ROUTER_AUTH_KEY
