# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: doppler-secret
stringData:
  token: ENC[AES256_GCM,data:kcWZa4DAsfyNMBhlfA9n75DKpoAqbW8SbavvYZKhH1c8ClHQ3NvZa1OLh+HVOmFapvKKakM=,iv:GEov2uaz/gCViKcYCvvYdii5540VxjWF6uFQbv9XE7U=,tag:xnHOI70k1XgiIF6qW+6YvA==,type:str]
sops:
  age:
    - recipient: age1hw68rfze8hyfdhg3g4pn4jakf8klvs9a24fa439h6f00wx29vccqm5jz0k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSDF5djlrQ1dHRmc5Qkd1
        RldqaG51ZXF2azh0emVMODVsdm1Zay96eFJNCnNHK0xwcWlMTXppUldzbyt2akpv
        OEh3TnpDUW5RMVo5ZlVweHNZZlR0WEUKLS0tIE9LbnNmS2VSWFgwaGd5aVFCcHBH
        Y0xnYWtGMGp1MmJFdUVUMXFZUWRGWXcKy0v9UDtY/z5VGEohNdQ1cDfAVEPJid9t
        NHnysb+R4KPJMK7QWQkAKc4sFYOboYsnAf+gwwLYJYPYeMueBKaasw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T14:46:07Z"
  mac: ENC[AES256_GCM,data:N1MAHjRX1bu+NBq1VbzOoT+bKnPdR1u18z+WkNiTW+qbdPpIjdw6sAKfYJhtHRCHxYR9eRUN5vNtyX+/F16hGxNyvsc0ILRmEgKREcnvrzYcb4pYTMS0A1DvlpIsCHeh3wI5+s6vT/EfKcyjnUEV5S3PE/k+ZshgPwRGqe/KxuA=,iv:UhPFAQm+3ZVBO21Y7TsVQJi9ZPG1ggyURzivwCkeALo=,tag:fQ53B7Mq2lJJ8yeatH1ivQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
