---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
  path: /apps/metallb-system/metallb/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: metallb-system
  prune: true
  interval: 15m
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-pools
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  path: /apps/metallb-system/metallb/pools
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: metallb-system
  prune: true
  interval: 15m
