---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cloudnative-pg
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.1@sha256:d844a09b25458ecb333208ba256df6baa320714257b9fb91752c2d8e75cc2f60
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: longhorn-backup-high-io
  postgresql:
    shared_preload_libraries:
      - vchord.so
    parameters:
      max_connections: '400'
      shared_buffers: 512MB
  resources:
    requests:
      cpu: 50m
    limits:
      memory: 1Gi
  monitoring:
    enablePodMonitor: true
