---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  path: /apps/node-feature-discovery/node-feature-discovery/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  timeout: 5m
# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: node-feature-discovery-config
#   namespace: flux-system
# spec:
#   path: /apps/node-feature-discovery/node-feature-discovery/config
#   prune: false
#   dependsOn:
#     - name: node-feature-discovery
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   interval: 30m
#   timeout: 5m
