---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: reloader
  values: # https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/README.md#parameters
    fullnameOverride: reloader
    reloader:
      reloadStrategy: annotations
      deployment:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi
      podMonitor:
        enabled: true
        namespace: "{{ .Release.Namespace }}"
