---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: immich-dragonfly
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.35.1@sha256:af7f7f1143269c7ffe4128451dff8f8fc09e157d885abcc9bafeec832d2928e6
  replicas: 1
  authentication:
    passwordFromSecret:
      name: immich-dragonfly-secret
      key: password
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=1
    # Required to make Dragonfly work with Immich
    # See: https://github.com/immich-app/immich/issues/2542#issuecomment-2564396901
    - --default_lua_flags=allow-undeclared-keys
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      memory: 256Mi  # min 256Mi per proactor_thread
  nodeSelector:
    feature.node.kubernetes.io/dragonfly.capable: "true"
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: dragonfly
