---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: immich-dragonfly
spec:
  selector:
    matchLabels:
      app: immich-dragonfly
  podTargetLabels:
    - app
  podMetricsEndpoints:
    - port: admin
