---
instance:
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: https://github.com/mcsrobert/homelab
    ref: refs/heads/main
    path: cluster
