---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:

    defaultSettings:
      backupTarget: "nfs://${NAS_IP}:/volume1/longhorn"

    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1

    longhornUI:
      replicas: 1

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Longhorn
        gethomepage.dev/icon: longhorn
        gethomepage.dev/description: Distributed, highly available Kubernetes storage
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/pod-selector: ""
      host: longhorn.${SECRET_DOMAIN}
      tls: true
      tlsSecret: longhorn-tls

    metrics:
      serviceMonitor:
        enabled: true
