---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    longhornUI:
      replicas: 1
    defaultBackupStore:
      backupTarget: "nfs://${NAS_IP}:/volume1/longhorn"
    metrics:
      serviceMonitor:
        enabled: true
    extraObjects:
      - apiVersion: snapshot.storage.k8s.io/v1
        kind: VolumeSnapshotClass
        metadata:
          name: longhorn
        driver: driver.longhorn.io
        deletionPolicy: Delete
      - apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: longhorn
          annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: Longhorn
            gethomepage.dev/icon: longhorn
            gethomepage.dev/description: Distributed, highly available Kubernetes storage
            gethomepage.dev/group: Infrastructure
            gethomepage.dev/pod-selector: ""
        spec:
          hostnames:
            - "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
          parentRefs:
            - name: traefik-gateway
              namespace: traefik
          rules:
            - backendRefs:
                - name: longhorn-frontend
                  port: 80
              filters:
                - type: ExtensionRef
                  extensionRef:
                    group: traefik.io
                    kind: Middleware
                    name: auth-chain
