---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: lint
on: push

permissions:
  contents: read

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      ansible: ${{ steps.filter.outputs.ansible }}
      kubernetes: ${{ steps.filter.outputs.kubernetes }}
      kubernetes_files: ${{ steps.filter.outputs.kubernetes_files }}
      markdown: ${{ steps.filter.outputs.markdown }}
      markdown_files: ${{ steps.filter.outputs.markdown_files }}
      yaml: ${{ steps.filter.outputs.yaml }}
      yaml_files: ${{ steps.filter.outputs.yaml_files }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          list-files: shell
          filters: |
            ansible:
              - 'ansible/**'
            kubernetes:
              - added|modified: 'kubernetes/**'
            markdown:
              - added|modified: '**/*.md'
            yaml:
              - added|modified: '**/*.yaml'
              - added|modified: '**/*.yml'

  ansible-lint:
    needs: changes
    if: ${{ needs.changes.outputs.ansible == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run ansible-lint
        uses: ansible/ansible-lint@665d9e07a1943254d2910faffc106adaf7ea7294 # v26.8.0
        with:
          working_directory: ansible

  # TODO: Should probably run on the output of flux local
  # kubeconform:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.kubernetes == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
  #     - name: Run kubeconform
  #       uses: docker://ghcr.io/yannh/kubeconform:v0.7.0
  #       with:
  #         entrypoint: /kubeconform
  #         args: >-
  #           -output json
  #           -summary
  #           -schema-location default
  #           -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
  #           -schema-location https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/{{.ResourceKind}}.json
  #           -ignore-filename-pattern resources/
  #           -ignore-filename-pattern helmfile\.ya?ml
  #           -ignore-filename-pattern helm-values\.ya?ml
  #           -ignore-filename-pattern transformer-config\.ya?ml
  #           -skip gateway.networking.k8s.io/v1/HTTPRoute
  #           ${{ needs.changes.outputs.kubernetes_files }}

  markdownlint:
    needs: changes
    if: ${{ needs.changes.outputs.markdown == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        with:
          globs: '${{ needs.changes.outputs.markdown_files }}'
          separator: ' '

  yamllint:
    needs: changes
    if: ${{ needs.changes.outputs.yaml == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: yamllint ${{ needs.changes.outputs.yaml_files }}
